### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#103]
Shutter pages prototype: https://hmrc-design-patterns.herokuapp.com/pages/shutter-pages/index

### Before the pattern is added to the [Design System](http://hmrc.github.io/assets-frontend/)
- [ ] content review of the pattern
- [ ] review by the HMRC working group
### For Design work
- [x] do we need as many examples as are displayed on this page
- [ ] discuss the header for shutter pages. Using the standard header with phase banners and HMRC logo may be overkill for this page
- [ ] examples are not displaying correctly 

## Related issues
- #54 Service closed
- #59 Technical difficulties
- #29 Service unavailable

**Comment by gavinwye** [comment]
## Number of examples
We discussed the number of examples on the page in our show and tell in Worthing and consensus was that more examples was better than just one. It's easier to do the right thing if there are concrete examples.

**Comment by gavinwye** [comment]
Branch created on assets frontend for this pattern https://github.com/hmrc/assets-frontend/tree/%23103-shutter-page-pattern

**Comment by stevenaproctor** [comment]
@gavinwye Same as #29.

**Comment by stevenaproctor** [comment]
This is published in the [GOV.UK Design System](https://design-system.service.gov.uk/patterns/service-unavailable-pages/). We have the Welsh version but there is no reason to keep a separate issue.
