### ISSUE TITLE
There is a problem with the service

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#105]
Prototype pattern page: https://hmrc-design-patterns.herokuapp.com/pages/500-pages/index

## Todo
- [ ] what header should 500 pages have?
- [ ] refine content
- [ ] do 500 pages need a report a problem link?

**Comment by alex16wake** [comment]
![image](https://user-images.githubusercontent.com/24815473/28574839-01f791d8-7147-11e7-9745-8853d0359b56.png)

**Comment by gavinwye** [comment]
Branch created on assets frontend for this pattern https://github.com/hmrc/assets-frontend/tree/%23105-500-page-pattern

**Comment by stevenaproctor** [comment]
@gavinwye Same as #59.

**Comment by stevenaproctor** [comment]
This is published in the [GOV.UK Design System](https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/). We have the Welsh version but there is no reason to keep a separate issue.
