### ISSUE TITLE
Page template

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#108]
This would be the HMRC page template for services using a specific version of the HMRC header #4

**Comment by adamliptrot-oc** [comment]
@gavinwye can you fix the link?

**Comment by gavinwye** [comment]
@adamliptrot-oc I've removed it as the page was not there.

**Comment by stevenaproctor** [comment]
This issue was closed because it is part of the main template for a service and does not need to be documented. The individual parts of the page – header, HMRC header, account header, footer – are documented separately.
