### ISSUE TITLE
Could not confirm identity

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#117]
IV fail pages

**Comment by gavinwye** [comment]
## Screens from the business registration prototype 

### You haven t completed your identity verification
![you haven t completed your identity verification](https://user-images.githubusercontent.com/868772/30028652-cd8570bc-917d-11e7-8c7c-c1af5a6dfcbc.png)

### Your session has timed out
![your session has timed out](https://user-images.githubusercontent.com/868772/30028653-cd873532-917d-11e7-8891-2c25aa61ab8e.png)

### We can't verify your information
![we can t verify your information](https://user-images.githubusercontent.com/868772/30028651-cd8199a6-917d-11e7-92b2-6f02c904a749.png)

### You've been locked out
![you ve been locked out](https://user-images.githubusercontent.com/868772/30028713-1a951bb4-917e-11e7-8e93-2d08d7fa6c60.png)

**Comment by gavinwye** [comment]
Added a branch to assets-frontend for this pattern https://github.com/hmrc/assets-frontend/tree/%23117-Identity-verification-failure

**Comment by claredmccarthy** [comment]
Current PTA IV fail/success pages

![iv failed matching](https://user-images.githubusercontent.com/30798630/30811226-7b80bfc8-a1ff-11e7-85b9-6056f4199bfd.png)
![iv incomplete](https://user-images.githubusercontent.com/30798630/30811231-7d599518-a1ff-11e7-8ba7-04d43be59ccd.png)
![iv insufficient evidence](https://user-images.githubusercontent.com/30798630/30811233-7ec7ff70-a1ff-11e7-848a-ef5829562030.png)
![iv locked out](https://user-images.githubusercontent.com/30798630/30811238-80c5435a-a1ff-11e7-8e3c-1f64731e286e.png)
![iv precondition failed](https://user-images.githubusercontent.com/30798630/30811241-8306164e-a1ff-11e7-9192-efa7acd0edaf.png)
![iv signed out](https://user-images.githubusercontent.com/30798630/30811245-854bae46-a1ff-11e7-84ef-c9393cd89379.png)
![iv technical issue](https://user-images.githubusercontent.com/30798630/30811248-8884c5f2-a1ff-11e7-9849-c6ace2b1d842.png)
![iv success](https://user-images.githubusercontent.com/30798630/30811260-8ab2e7fa-a1ff-11e7-9c20-4953deda76e2.png)

**Comment by spangled** [comment]
IV fail pages from P800/taxcalc.

IV_tryagain
The first one is displayed when the user's identity cannot be confirmed the first or second time

IV_failed
The second one is displayed when the user fails a third time - they are locked out and are asked to come back in 24 hours' time.

![iv_tryagain](https://user-images.githubusercontent.com/10713095/31014406-9620440a-a512-11e7-81a2-e3fb408a1220.png)

![iv_failed](https://user-images.githubusercontent.com/10713095/31014411-9b7a11b0-a512-11e7-9766-5ca4e83a0903.png)

**Comment by olirose** [comment]
Current MTD sign up/registration IV error pages (in order):
IV incomplete
IV failed matching
IV technical issue
IV timed out
IV locked out
IV insufficient evidence
IV precondition failed
IV success


![image](https://user-images.githubusercontent.com/31846170/31115014-8a57c14e-a818-11e7-9a62-7f659e1f77a9.png)

![image](https://user-images.githubusercontent.com/31846170/31115035-a6c9f608-a818-11e7-8dba-f77ea01c1c70.png)

![image](https://user-images.githubusercontent.com/31846170/31115063-bf88a072-a818-11e7-84ab-f3717de0e0ee.png)

![image](https://user-images.githubusercontent.com/31846170/31115096-e0f96c82-a818-11e7-9875-c3555108fcab.png)

![image](https://user-images.githubusercontent.com/31846170/31115109-ef630878-a818-11e7-971b-4e7f76885549.png)

![image](https://user-images.githubusercontent.com/31846170/31115130-fc717f2c-a818-11e7-97a1-ff9e7b433c3c.png)

![image](https://user-images.githubusercontent.com/31846170/31115186-3c0674c6-a819-11e7-8955-2898dafec98b.png)

![image](https://user-images.githubusercontent.com/31846170/31115195-44933b56-a819-11e7-8c0e-5073ba1b19bc.png)

**Comment by stevenaproctor** [comment]
@gavinwye Do people know they were in an identity check? Will everyone understand identity?

"timed out" and "locked out" are web jargon.

**Comment by gordonmcmullan** [comment]
@stevenaproctor it might make sense to align the "timed out" language with the language which is used in the [Session Timeout Prompt](https://github.com/hmrc/design-patterns/issues/89) pattern

**Comment by gavinwye** [comment]
@stevenaproctor yes content for all of these things should be refined.

**Comment by elenecid** [comment]
These pages (error/failure/success etc.) are held by individual services and there's definitely a need to show a consistent content across all the services that use them. 

When a service makes use of IV, is prompted with a "start page" that explains to the user that they need to prove their identity. @stevenaproctor Do you think that even users are warned with this "start page" at the beginning of the process, are not aware of the fact that they've gone through an identity check? 
This page belongs to IV -even I could see the benefit of being held by individual services so they adjust the content to their journeys. In any of the cases, the content could be improved according to users understanding.

**Comment by gordonmcmullan** [comment]
Discussion summary from  the hackday

![img_20180312_151117](https://user-images.githubusercontent.com/234825/37339703-76256dc4-26b3-11e8-8659-d222b75706c6.jpg)

**Comment by jennifer-hodgson** [comment]
From what I understand, this pattern is a means of telling users that the identity verification process has failed and that they must go back and repeat the process or contact HMRC to verify their identity in another way. Therefore, the success screen isn't a relevant example here. 

Also, "Confirm who you are" doesn't feel like it describes fully what's going on here. It feels more like one of the GDS-style task-based patterns: "Help users to confirm who they are when identity verification does not work", for example.

**Comment by gordonmcmullan** [comment]
@jennifer-hodgson There is also a success page https://user-images.githubusercontent.com/31846170/31115195-44933b56-a819-11e7-8c0e-5073ba1b19bc.png

**Comment by stevenaproctor** [comment]
@jennifer-hodgson I would hate to even use the words 'identify verification'. I like 'Help people confirm who they are'. Worth testing.

**Comment by jennifer-hodgson** [comment]
@stevenaproctor I feel you on the jargon. I think it's important to specify the particular circumstances in which this pattern is used, though. Otherwise, there could, hypothetically, be confusion around the process for verifying peoples' identities in services - ie. it should be clear that this is used when another process has not worked. Also, because this will always appear in connection with the identity verification process, I suggest we should name the thing we are referring to.

**Comment by jennifer-hodgson** [comment]
@gordonmcmullan I'll merge this example, if there's an existing pattern for success.

**Comment by stevenaproctor** [comment]
@jennifer-hodgson How about 'Help users when we cannot confirm who they are'?

**Comment by jennifer-hodgson** [comment]
Works for me, cheers!

**Comment by jennifer-hodgson** [comment]
Are there any instances where this pattern is not connected to GOV.UK Verify, ie. where it is used after another form of identity check has failed?

**Comment by stevenaproctor** [comment]
@jennifer-hodgson It is used after Government Gateway but is similar #132 as well which is neither Government Gateway or Verify.

**Comment by stevenaproctor** [comment]
@jennifer-hodgson This pattern only applies to Government Gateway. GOV.UK Verify is totally separate.

#132 is similar in that it is someone like an agent looking up someone else inside a service. The content pattern is similar but the use case slightly different.

The name is a problem. Do we need to include a 'success' page? Is that not a normal 'confirmation' page?

**Comment by jennifer-hodgson** [comment]
In the process of documenting this pattern, it appears to me that two of the variants mentioned above might be separate patterns (in that they are not unique to this particular pattern, but applicable more generally). These are:
* Technical error (which we already have)
* You have been signed out

**Comment by stevenaproctor** [comment]
#148 is a separate pattern for the success page.

The timed out and technical problem pages should follow patterns #89 and #105.

**Comment by stevenaproctor** [comment]
@edmorley Did you have to enter any details to prove your identity? Things like passport number or information from your most recent P60?

**Comment by edmorley** [comment]
Hi Steven, thank you for the reply. 

There were no prompts for additional information at all.

The flow was:
* https://www.gov.uk/tell-hmrc-change-address -> click "Start now"
* Enter username/password
* Enter access code
* "Set security backup" -> I clicked "I can't do this right now" (I don't want to since I'd have to install the app)
* "You didn't set your security backup today. We'll remind you next time you sign in." -> I clicked "Continue"
* The page then redirects multiple times, the intermediate URLs being:
  - `https://www.tax.service.gov.uk/mdtp/uplift?origin=PERTAX&confidenceLevel=200&completionURL=%2Fpersonal-account%2Fidentity-check-complete%3FcontinueUrl%3D%252Fpersonal-account%252Fpersonal-details&failureURL=%2Fpersonal-account%2Fidentity-check-complete%3FcontinueUrl%3D%252Fpersonal-account%252Fpersonal-details`
  - `https://www.tax.service.gov.uk/identity-verification/complete/precondition-failed?redirectUrl=%2Fpersonal-account%2Fidentity-check-complete%3FcontinueUrl%3D%252Fpersonal-account%252Fpersonal-details&token=REDACTED`
* Then the final error "We cannot confirm your identity" (URL: `https://www.tax.service.gov.uk/personal-account/identity-check-complete?continueUrl=/personal-account/personal-details&journeyId=REDACTED`)

I get the same error/intermediate pages if I start via https://www.gov.uk/personal-tax-account too.

**Comment by stevenaproctor** [comment]
@edmorley You should only get one of these pages when your identity is being confirmed. I will take a look and see what is happening.

**Comment by edmorley** [comment]
@tasmanarmstrong - done :-)

**Comment by BA1HMRC** [comment]
Hello @edmorley, thanks for doing this can you please email me to this address "victoria.kio@digital.hmrc.gov.uk" with the exact screenshots, as well the URL, with the journey id in the link, that will be very helpful to drill down your events on our diagnostics tools, thank you!

**Comment by stevenaproctor** [comment]
This is a page from a HMRC service but it could be relevant to all government services that use identity assurance verification for their service.

**Comment by mikeash82** [comment]
Nopw part of  [create account](https://github.com/alphagov/govuk-design-system-backlog/issues/41) and [identifying users](https://github.com/alphagov/govuk-design-system-backlog/issues/25) on the GOV.UK Design System backlog.
