### ISSUE TITLE
Multiple file uploads

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#118]
Being worked on by the SDES team in Shipley

**Comment by stevenaproctor** [comment]
@gavinwye Similar to #68.

**Comment by gavinwye** [comment]
Yes, we should probably combine these two into one file upload pattern that counts for multiples as well as singles.

**Comment by jennifer-hodgson** [comment]
This is covered by [file upload](https://github.com/hmrc/design-patterns/issues/68).
