### ISSUE TITLE
Passport details

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#12]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22465980/88be4a30-e7be-11e6-8c53-d2527d4dfe3b.png)

**Comment by stevenaproctor** [comment]
@gavinwye The opening paragraph says "exactly as they appear on your passport" so do we need the hint text under surname and given names? If we do, should given names not say "exactly"?

Does the expiry date need leading zeroes in the day?
Does the expiry date allow FEB, 2 and 02?
Does the expiry date allow 21 and 2021?

**Comment by stevenaproctor** [comment]
This issue was closed because it is part of identify verification microservice. It does not need to be documented.

**Comment by timpaul** [comment]
Hi @stevenaproctor - I know you closed this as it's covered by a HMRC microservice. Is it still worth documenting in the GOV.UK Design System though, so other departments can follow the pattern?

If so, do you know if the screenshot above is still accurate?

**Comment by stevenaproctor** [comment]
Hi @timpaul, We could reopen the issue if we are sure we want people following the same pattern. I wonder if there is something in apply for a passport online. I registered a new account to get the latest screenshot.
![your uk passport](https://user-images.githubusercontent.com/11977962/37033243-36d788da-213d-11e8-94a9-4ad6b0d6f41c.png)
