### ISSUE TITLE
Niche start pages

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#124]

**Comment by adamliptrot-oc** [comment]
Elaboration?

**Comment by gavinwye** [comment]
This issue was raised as a result of a conversation with the GOV.UK content team. They would like to clarify the rules about green buttons and links. I think this would be useful to have a pattern so people can include these pages in their prototype for UR.

**Comment by stevenaproctor** [comment]
Added comment to #21 and closed this issue.
