### ISSUE TITLE
HMRC Tax terms

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#125]
List of tax terms specific to HMRC

**Comment by stevenaproctor** [comment]
@gavinwye These could be added to the content style guide. See https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#self-assessment-online

**Comment by gavinwye** [comment]
@stevenaproctor yes but I think an initial step would be to get them in the design system

**Comment by stevenaproctor** [comment]
This issue has been closed because this information should be available in the GOV.UK content style guide or some internal system.

**Comment by jennifer-hodgson** [comment]
This is now covered by the HMRC content style guide.
