### ISSUE TITLE
Reveal

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#13]
# Description
Conditionally revealing content

# Screenshot
![have you made any improvements to the property](https://cloud.githubusercontent.com/assets/2305016/22465977/25cb48d6-e7b6-11e6-84cc-c29ac97d11b2.png)

# GOV.UK Pattern
https://govuk-elements.herokuapp.com/form-elements/#form-toggle-content

# Research Questions
This seems to be a pattern around "what do we do when the user can't use the service to perform the action they want to perform?"

**Comment by gavinwye** [comment]
Closing this as it's a gov.uk thing
