### ISSUE TITLE
Contractions 

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#130]
Describe HMRC's position on contractions so that we can be consistent in our use of them

**Comment by stevenaproctor** [comment]
@gavinwye 

Here is a summary of what has been in Basecamp and other mailing lists about contractions.

The main contractions people struggle with are negative contractions or colloquialisms. Personally, I have seen people with low literacy, low vision and dyslexia struggle with all kinds of contractions. I have watched people read can't and don't and say can and do. I remember one person who found it difficult to see apostrophes and saw I'll and we'll as ill and well.

The Department for Work and Pensions found that people with learning difficulties struggled to understand the contractions and support workers explained some people rely on reading the "not" to understand what is being said.

A few organisations like Home Office and Access UK have found this is the same with non-native English speakers.

Joe Lanman from GDS referred to research on Verify and other places that showed "contractions are hard to read, and writing the words out in full significantly increases understanding".

Contractions might not stop someone from completing a transaction, but it will take them longer and require more effort.

GDS generally recommend to avoid them in services, although this is not in guidance, but use them on GOV.UK.

Writing content for everyone
https://gds.blog.gov.uk/2016/02/23/writing-content-for-everyone/

Using contractions could be making your writing inaccessible
https://medium.com/@joanne.schofield/using-contractions-could-be-making-your-writing-inaccessible-4034bb3cd76a

**Comment by stevenaproctor** [comment]
There is a section about [contractions in the style guide](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#contractions) and [writing for GOV.UK](https://www.gov.uk/guidance/content-design/writing-for-gov-uk#contractions).

**Comment by stevenaproctor** [comment]
How to make information accessible (page 34)
![page-34](https://user-images.githubusercontent.com/11977962/37153516-dddd1a8a-22d4-11e8-9e32-37dec8e9a9a1.PNG)

**Comment by gordonmcmullan** [comment]
Discussion Summary from the Hackday

![img_20180312_161148](https://user-images.githubusercontent.com/234825/37339173-a2aad6c4-26b1-11e8-837f-7519f7b999ce.jpg)

**Comment by stevenaproctor** [comment]
This is a cross-government thing but is content design guidance rather than a pattern. We could keep it here or add it to the GOV.UK Design System backlog.
