### ISSUE TITLE
Form Valdiation - Sub level inputs

### ISSUE THREAD

**Issue by Fenwick17** [hmrc/design-patterns#131]
Some forms have radio buttons when clicked display a sub level input. Currently there is not a pattern in place for error validation with these form types.
A current implementation is: 
![errorvalidation](https://user-images.githubusercontent.com/11258920/31121877-c7c26494-a831-11e7-97fa-583443000d09.png)
An alternative is:
![errorvalidation2](https://user-images.githubusercontent.com/11258920/31121885-cd5d2150-a831-11e7-819b-7c5f582b2e3a.png)
An alternative currently used design: 
![errorvalidation3](https://user-images.githubusercontent.com/11258920/31123431-cf865d7e-a837-11e7-8ddb-ec5db28060cc.png)

**Comment by adamliptrot-oc** [comment]
@rpowis this is what I was talking about when I said about interaction between components (panel and error) in AF/Elements

**Comment by rpowis** [comment]
Thanks @Fenwick17. And I see what you mean now @adamliptrot-oc.

I wouldn't say that validation is a pattern or even a component in its own right. Validation should be a consideration of a pattern's implementation and most likely will be pattern specific. It looks like part of a payment pattern, but different to [Make a payment](https://github.com/hmrc/design-patterns/issues/62)?

**Comment by gavinwye** [comment]
This should be part of a validation pattern but each component should have validation thought about at a component level.
