### ISSUE TITLE
Telling a user that known facts do not match HMRC records

### ISSUE THREAD

**Issue by benwatsonuk** [hmrc/design-patterns#132]
I don't believe that we have a pattern in existence to play back to users that known facts supplied do not match those held on HMRC systems.

Specifically, in the cases I am looking at, an agent is supplying 'known facts' to satisfy HMRC that a sufficient level of detail is known about a taxpayer. In the event that these details are not the same as those on record on a particular system, we need to make the user aware whilst not revealing the specific points of failure. 

One particular challenge to bear in mind is that the 'known facts' may not be incorrect, they may simply be inconsistent with our records.

**Comment by elenecid** [comment]
At the moment, and I’m merely speaking about Individuals, if they fail Identity Verification, a failure page is shown. This page sits under the service that is making use of IV (IV is a micro service but doesn’t hold a failure page). This means that each service shows the content that it’s considered most appropriate depending on their user journey. 
IV shows validation messages when the number of letters or the format doesn’t match. 
At the same time, it’s not possible to make a difference between the errors when the data doesn’t match our records, or our records are not up to date. 
I believe it would be good to have a consistent IV failure page across services, or/and research if IV should hold them.
I believe you may be facing a similar problem in the case of agents?

**Comment by rpowis** [comment]
This relates to #117

**Comment by stevenaproctor** [comment]
The issue was closed because it is a version of an identity verification failure page – see #117.

**Comment by benwatsonuk** [comment]
@stevenaproctor - I don't think #117 covers this exact scenario. 

In the context of a tax agent, the verification process isn't about the individual identifying themselves but a user identifying another individual (a third party). I don't believe item 117 covers these use cases.

**Comment by stevenaproctor** [comment]
@benwatsonuk I think we should have a pattern about identity verification that includes the agent examples too. Does that sound OK?
