### ISSUE TITLE
Inset Text

### ISSUE THREAD

**Issue by jenrahm** [hmrc/design-patterns#133]
![image](https://user-images.githubusercontent.com/33151742/32100554-235bea90-bb0c-11e7-87ec-b0bd803d819d.png)

Observed recently in usability testing that user do not notice this pattern when notifying users of updated content within the P800 Tax Calc (CY-1) service. Within this service it's important to alert users that there has been a change in the amount of tax they owe. 

![image](https://user-images.githubusercontent.com/33151742/32100672-8f96b398-bb0c-11e7-94ec-8b1c69f446f1.png)

Feedback from User Research session shows that users did not see the inset text despite understanding the rest of the information on the page. 

Users would not have seen or navigated to the link within the inset text without being prompted to go back to this page after interacting with rest of service.

I've also seen this pattern fail within the Medical Benefit service, where we needed instruct the user to check with their employer the amount received before submitting the transaction.

**Comment by stevenaproctor** [comment]
@jenrahm I have seen people not notice content in an inset panel in services and GOV.UK content. I think this is why people use the legal icon and bold text instead – it better draws people's attention.

**Comment by jenrahm** [comment]
@stevenaproctor  We currently use the legal icon for deadline information. I've used the blue 'i' icon in in a previous service as an alternative, which worked.

Currently within the P800 service we're looking at just letting the user know there's new and updated information for them using headings and body content above the information.

**Comment by vickytnz** [comment]
Surely this is less about inset and more about information hierarchy? Nothing really stands a chance just before a big figure with a £ sign?

**Comment by jenrahm** [comment]
@vickytnz  user's also didn't notice it here in the medben service

![image](https://user-images.githubusercontent.com/33151742/32168144-4d5f1c1e-bd63-11e7-8b01-a5ea3b39785f.png)

**Comment by gavinwye** [comment]
I wonder if in the last example they would have noticed if the inset had been between the benefit value and the question?

**Comment by jenrahm** [comment]
@gavinwye We did try that in medben, as well hint text in that position, which users also didn't notice. 
Then we moved to using the blue 'i'

**Comment by vickytnz** [comment]
I'm surprised to see a playback and confirm in close proximity to 'you may need to ask' - when users saw this did they expect this? I don't know what the rest of the journey, but mid-service seems like a strange point to get these two things (I'm not sure where the information that's being confirmed came from)

(While inset texts do need to be used judiciously in services where every word should work hard to even be there, I wonder if there are bigger information clashes going on)

**Comment by stevenaproctor** [comment]
The blue 'i' is not in elements so it tends to get styled and used inconsistently.

The only place I have ever seen it in guidance is as an [advisory in Govspeak content](https://govuk-static.herokuapp.com/component-guide/govspeak/advisory).

I know in usability testing sessions, some people select the 'i'. Because of the blue colour they thought it was a link.

**Comment by gavinwye** [comment]
I've been investigating this and there are two different styles for inset text in elements
```
.panel-border-wide {
  border-left-width: 10px;
}

// Used to show the left edge of "toggled" content
.panel-border-narrow {
  border-left-width: 5px;
}
```
https://github.com/alphagov/govuk_elements/blob/d30ee5a829a515e5b4f323fa1f7c27e75617cb33/assets/sass/elements/_panels.scss#L24

Resulting in a 5-pixel difference between the two styles 
![screenshot 2017-10-31 15 26 37](https://user-images.githubusercontent.com/868772/32232568-3de04dce-be50-11e7-891a-d93b06f5c596.png)

Elements only show the wider bar. I assume that this is down to someone's opinion of what looks better. 

The examples provided above show different widths. Has any research been done to understand if the 5px difference makes a difference? Comparing them side by side I find the 10px version stands out much more.

**Comment by jenrahm** [comment]
The P800 uses is 10px, the med ben is 5px. Both times users didn't notice it (perhaps because of the bold £ figure of money that we're displaying to the user...) 

That aside I don't think that this pattern serves it's purpose of 'drawing attention to important content on the page' as stated in the patterns .... Users might see it and choose not to actually read it/properly look at it because it doesn't stand out, the grey indent looks passive and like it could just be generic content not specific to them.

**Comment by gavinwye** [comment]
> That aside I don't think that this pattern serves it's purpose of 'drawing attention to important content on the page' as stated in the patterns .... Users might see it and choose not to actually read it/properly look at it because it doesn't stand out, the grey indent looks passive and like it could just be generic content not specific to them.

Yea I agree. I actually think it's what some sites use to differentiate an `<aside>` element. GitHub is using it to show quoted text above. 

It's all a bit confusing.

**Comment by gavinwye** [comment]
@jenrahm did you find a better solution at all? Something that we could use as an alternative?

**Comment by jenrahm** [comment]
We're using the blue 'i' icon in P800 to let users know about their payment information.... (some people use this with bold text)

![image](https://user-images.githubusercontent.com/33151742/32235335-196385c2-be57-11e7-9996-8dd956cb8d19.png)

The legal warning to tell users about deadline information...
![image](https://user-images.githubusercontent.com/33151742/32235317-0a2bf0bc-be57-11e7-933e-e23f8dc64b6f.png)

Tomorrow we're testing headings as a way of highlighting a change....

![image](https://user-images.githubusercontent.com/33151742/32235433-610a748a-be57-11e7-9c27-3f0f670e0301.png)

This is purely in P800, surely other services must have experienced a similar issue...

**Comment by philsherry** [comment]
That blue icon has never looked good to me, but seeing it next to the black one just makes it look worse. If it must exist, then can it at least be a uniform size? 

> _some_ people use this with bold text

@jenrahm Only some? Why the inconsistency? How have you conveyed their extra attention for screen readers?

@gavinwye Can we add something about only using one of these things on a page? I've seen a few instances where they're littered all over the place, rendering them almost redundant.

**Comment by philsherry** [comment]
@gavinwye If the narrow one is only for use within a `details` element, then I'd suggest some specificity to confine it. `details .panel-border-narrow` would be fine.

**Comment by jenrahm** [comment]
@philsherry  Yep, we're looking at making these icons the same size for consistency. 

By 'some people' I meant I've seen designers (not users) use this pattern with bold in other services. 

Agree that that they should be consistent and their use limited so it doesn't look spammy/irrelevant clutter.

**Comment by philsherry** [comment]
@jenrahm Yeah, I understood how you meant it. 

Some designers favour bold text, some don't. That's irrelevant if the pattern states one over the other. We need to get better at using the available tools and stop tweaking things to suit personal preference.

**Comment by jenrahm** [comment]
@philsherry Yeah, I've seen it inside a blue or grey alert style banner as well as the legal text in a yellow alert/banner. Agreed the styling should be nailed down.

**Comment by gavinwye** [comment]
@philsherry Yes using things like this sparingly should be covered in the documentation for the component.

**Comment by gavinwye** [comment]
Inset text is going to be deprecated in the new GOV.UK design system https://github.com/alphagov/govuk-frontend/pull/363

**Comment by stevenaproctor** [comment]
This issue has been closed because it is either going to be deprecated or be in the GOV.UK Design System.

**Comment by jennifer-hodgson** [comment]
Inset text is [published on the GOV.UK Design System](https://design-system.service.gov.uk/components/inset-text/).
