### ISSUE TITLE
Track something in HMRC

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#139]
Use this pattern to help users to track a thing that they are doing or have sent to HMRC

Tracking forms
![image](https://cloud.githubusercontent.com/assets/868772/22469578/691c99e2-e7c4-11e6-9ec3-945063ab4110.png)

Your progress in an application
![image](https://cloud.githubusercontent.com/assets/868772/22469587/7667e5fc-e7c4-11e6-85b5-54b29436a3d9.png)

**Comment by stevenaproctor** [comment]
The issue was closed because it is a separate microservice for tracking iForms and a version of a task list  – see #38.
