### ISSUE TITLE
Overdue

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#14]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22466034/b3262f86-e7be-11e6-8d29-185d3059240e.png)

**Comment by rpowis** [comment]
Is this an HMRC specific pattern or a Government-wide thing? Do other Government departments need to tell users that something is overdue?

**Comment by stevenaproctor** [comment]
@gavinwye I am sure something similar is done in Self Assessment and the business tax account. I do not have screenshots.

**Comment by stevenaproctor** [comment]
This issue was closed because there was not enough information and it is currently only used in one service.
