### ISSUE TITLE
Open links in a new window or tab

### ISSUE THREAD

**Issue by sophieottaway** [hmrc/design-patterns#141]
There are several different approaches that we could use to handle links that open in a new tab - to effectively communicate the destination of the link to users with and without visual impairments.

Are we able to agree on a pattern?

Three suggestions I've heard are:

1. Put the "(Opens in a new window or tab)" as part of the link itself (Chris Moore recommended)
2. Put the "(Opens in a new window or tab)" as part of the link itself but add a style to remove the underline (Joe Lanman, GDS suggestion)
3. Use a span with class of visually hidden inside the link to help users with screen readers and standard text outside the link for all other users (Ed Horsford, GDS suggestion)

**Comment by stevenaproctor** [comment]
@sophieottaway Chris's recommendation comes from [G201: Giving users advanced warning when opening a new window](https://www.w3.org/TR/WCAG20-TECHS/G201.html), which is part of WCAG 2.0. 

Not sure if we should remove the underline. It will make the link look odd. The other option seems over-engineered and clashes with the "don't write content that works specifically for screen readers, write content that works well for everyone" idea from [How to create content that works well with screen readers](https://accessibility.blog.gov.uk/2017/02/08/advice-for-creating-content-that-works-well-with-screen-readers/).

I have seen research and usability testing where opening links in a new window or tab confuses people who do not understand why the back button is disabled. This happens even when you warn people it is going to happen.

What user need does opening the link in a new window or tab solve?

**Comment by vickytnz** [comment]
given that Sophie's work is for developers, it's perhaps closer to designing for internal users

**Comment by stevenaproctor** [comment]
I'm not sure there is a different need between the different users. I think a pattern would apply for all users.

**Comment by joelanman** [comment]
One time it might help to open in a new tab (not sure there's any point to saying 'window' too) is in a page where the user could lose entered information if they navigated away. It may also be useful in a transaction where the user was worried they could lose information (even if they wouldn't) but that would have to be researched.

In general I'd like to stay away from new tabs, as mentioned people can get stuck when the back button doesn't work in the new tab.

**Comment by stevenaproctor** [comment]
I would say "window or tab" because we do not know someone's browser settings.

**Comment by ian-leggett** [comment]
Found this article which may help however it seems to point to the above comments anyway - https://www.webcredible.com/blog/beware-opening-links-new-window/

**Comment by stevenaproctor** [comment]
@ian-leggett It is a security risk too unless you use some extra code. https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by ian-leggett** [comment]
I spoke with David Birchall(Frontender) who uses it in - https://github.com/hmrc/api-documentation-prototype/commits?author=davidbirchall he said that this pattern came out of an accessibility workshop he went to in Newcastle on SDES

**Comment by adamliptrot-oc** [comment]
@ian-leggett that workshop was run by me

**Comment by gordonmcmullan** [comment]
This is the summary of the discussion of this pattern at the hackday

![img_20180312_132606](https://user-images.githubusercontent.com/234825/37339038-34437bd2-26b1-11e8-97a2-fc0e4fbef0bc.jpg)

**Comment by stevenaproctor** [comment]
This is a cross-government thing and is on the [GOV.UK Design System backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/156).

Not sure it needs a separate component or pattern. More likely it needs some information added to [links](https://design-system.service.gov.uk/styles/typography/#links).

**Comment by mikeash82** [comment]
Upstreamed to the GOV.UK issues backlog https://github.com/alphagov/govuk-design-system-backlog/issues/156
