### ISSUE TITLE
Running tally

### ISSUE THREAD

**Issue by jennifer-hodgson** [hmrc/design-patterns#145]
# Running tally

## Overview
This pattern is used to display in summary form information already entered by a user. Its purpose is to remind users of the information they have already entered, to reassure them that this information been saved.

[This pattern arose following the HMRC design system hackday. It is related to the [add to a list](https://github.com/hmrc/design-patterns/issues/31) pattern.]

**Comment by adamliptrot-oc** [comment]
This is currently used on the Residence Nil Rate Band Calculator
![image](https://user-images.githubusercontent.com/14074579/37716781-3895fa5e-2d17-11e8-882c-3f3ea5bf8861.png)

**Comment by MarkKeeling** [comment]
Isn't this the GDS smart down (smart answers) pattern?

**Comment by stevenaproctor** [comment]
It is similar to the smart answers pattern.

This is what that looks like.

![image](https://user-images.githubusercontent.com/11977962/37762588-a5695232-2db4-11e8-92e4-3cec95129a2a.png)

**Comment by MarkKeeling** [comment]
This is the latest smart answer pattern, smart down.

![image](https://user-images.githubusercontent.com/21083385/37767023-a5a82aaa-2dc0-11e8-95c4-5d936435764b.png)

**Comment by stevenaproctor** [comment]
@MarkKeeling I took that screenshot today so it looks like there is more than one pattern.

Just to mention that this pattern has accessibility problems. One was having the previous questions above the new question. It is awful on a mobile phone and is a lot of information for a screen reader to read over and over again. I think is why smart down was introduced.

Another is that the screens are cluttered, which affects everyone but especially people with learning disabilities and mental health conditions.

**Comment by MarkKeeling** [comment]
I agree @stevenaproctor hence the iteration to smart down:

https://insidegovuk.blog.gov.uk/2014/11/06/improvements-to-smart-answers/

**Comment by stevenaproctor** [comment]
See #31
