### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#15]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22466083/ec5b16cc-e7be-11e6-83e8-6c09291bc733.png)

# GOV.UK Pattern

https://www.gov.uk/service-manual/user-centred-design/resources/patterns/help-text.html#hidden-help-text

**Comment by stevenaproctor** [comment]
@gavinwye I think this is a GOV.UK pattern. It is in the service manual.

**Comment by gavinwye** [comment]
this is a GOV.UK pattern
