### ISSUE TITLE
Make digital to print journeys consistent

### ISSUE THREAD

**Issue by jennifer-hodgson** [hmrc/design-patterns#150]
## Overview
There are several services where, within end-to-end journeys, users may move between digital and print (and vice versa). We need to find a way to reconcile digital and print standards and norms in order to ensure a consistent user experience, as well as ensuring that we meet the specific user needs of the service. 

This issue was raised as part of the HMRC Working Group, where @russellthorn demonstrated a digital to print user journey from Inheritance Tax. As part of this journey, users download a print pdf estate report. Russell raised questions around the use of the HMRC logo in this context:
* should it be displayed in line with rules surrounding letters
* moreover, is there a user need to display the HMRC logo on the letter?
* if we display the HMRC logo in the print output, do we also need to carry that consistency through the digital journey by using the HMRC logo here too?

**Comment by jennifer-hodgson** [comment]
This pattern differs significantly from [#116 Print this page](https://github.com/hmrc/design-patterns/issues/116). I wonder, though, whether it could be merged with [#49 Certificate](https://github.com/hmrc/design-patterns/issues/49) - because the two share important user needs - key different seems to be to do with the "officialness", which could be a variant?

**Comment by russellthorn** [comment]
Merging into another issue has it's ups and down sides.
- Ups: decluttering issues (reducing duplication), related things in 1 place (easier to find)
- Downs: the issue/subject can lose focus and importance when merged into another issue and may get overlooked.

I'm not convinced [#49 Certificate](https://github.com/hmrc/design-patterns/issues/49) is is similar enough not muddy the waters between the 2 issues. [#116 Print this page](https://github.com/hmrc/design-patterns/issues/116), possibly. If it was renamed and clear differentiation between the pattern of printing pages and document, and giving print and digital consistent branding. I think I'm siding with merge into #116 Print this page. But have no strong opinion on that either.

**Comment by jennifer-hodgson** [comment]
Update on this.                  

Conversations with our comms team are ongoing, but for now: designers should aim for consistency across the digital to print journey, therefore applying the GOV.UK and HMRC digital patterns and standards to print outcomes of digital journeys.

**Comment by jennifer-hodgson** [comment]
This feels x-gov - thoughts?

**Comment by stevenaproctor** [comment]
Definitely. Most government departments have digital services that interact with print services.

**Comment by mikeash82** [comment]
Upstreamed to the GOV.UK issues backlog https://github.com/alphagov/govuk-design-system-backlog/issues/163
