### ISSUE TITLE
Filter results

### ISSUE THREAD

**Issue by fordie** [hmrc/design-patterns#151]
# Filter results
# CCA

## Overview
This pattern allows a user to search or filter a list of items that have been returned by the system, for instance looking for only pubs or properties in a certain postcode that are in a list of properties. This is similar to search, but the user will already have been presented with a list of results that they want to reduce.

![find-a-client](https://user-images.githubusercontent.com/494985/41900478-bd3bc7ce-7926-11e8-9546-3387fc72dd1a.png)

![property filter](https://user-images.githubusercontent.com/494985/41901805-c6ad8574-7929-11e8-9c20-8b32e7b5e388.png)

## Is it useful and unique?
Filtering data seems to be a need on a number of services

## Research on this pattern
Not sure what research has been carried out so far, will check with emac-BSL team

**Comment by stevenaproctor** [comment]
@fordie Any updates for this issue?

**Comment by fordie** [comment]
Our UR is off until Thursday, so I'll catch up with her then. They did a little bit of testing in our last round of research, but I'll ask them to do some more next week.

**Comment by benwakefield** [comment]
@stevenaproctor We're using this approach to refine results where usual closed checkbox filtering isn't appropriate, the prototype should be out for testing in the coming weeks.
<img width="945" alt="screen shot 2018-09-27 at 07 58 21" src="https://user-images.githubusercontent.com/7381460/46128418-4ca40500-c22b-11e8-907a-11c56d918fee.png">

**Comment by jennifer-hodgson** [comment]
Filter is on the [GOV.UK Design System backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/133).

**Comment by mikeash82** [comment]
Moved to [Filter a list ](https://github.com/alphagov/govuk-design-system-backlog/issues/133)on the GOV.UK issues backlog
