### ISSUE TITLE
Content is not available in Welsh

### ISSUE THREAD

**Issue by stevenaproctor** [hmrc/design-patterns#152]
## Overview

This component will help Welsh language users when not content is not available in Welsh.

![image](https://user-images.githubusercontent.com/11977962/43510725-6d62d954-956e-11e8-93c9-1283f3d1aa05.png)

In English, this means "This page is only available in English at the moment." The link lets you close the banner and means "Do not show this again".

![image](https://user-images.githubusercontent.com/11977962/43511132-8e8f525a-956f-11e8-8430-098703f1576a.png)

In English, this means "Some of our pages have yet to be translated into Welsh." This more general version is used in the personal tax account as a disclaimer for the whole account.
 
## Is it useful and unique?

This information will need to be used in all services that are not completely translated in to Welsh. The blue banner is an [alert](https://github.com/alphagov/govuk-design-system-backlog/issues/2) that is not part of the GOV.UK Design System or HMRC Design System yet.

## Research on this pattern

The content has been agreed with and translated by the Welsh Language Unit.

The blue banner is in older versions of assets frontend as an [attorney banner](https://hmrc-component-library.herokuapp.com/section-attorney-banner.html) and an [alert-info notification](https://hmrc-component-library.herokuapp.com/section-notification.html).

I do not have any research but the banner is usually above the `h1` and is often missed or ignored.

**Comment by stevenaproctor** [comment]
Not sure this is HMRC only. Other government departments need to translate services and content into Welsh so this would be useful for them. Relates to [supporting multiple languages](https://github.com/alphagov/govuk-design-system-backlog/issues/99) in the GOV.UK Design System backlog.

**Comment by mikeash82** [comment]
Issue has been added to the [Supporting multiple languages](https://github.com/alphagov/govuk-design-system-backlog/issues/99) issue in the GOV.UK backlog
