### ISSUE TITLE
Ask the user for their consent

### ISSUE THREAD

**Issue by jennifer-hodgson** [hmrc/design-patterns#154]

**Comment by stevenaproctor** [comment]
Not HMRC only. [Share personal data](https://github.com/alphagov/govuk-design-system-backlog/issues/93) is on the GOV.UK Design System backlog and is similar.

**Comment by mikeash82** [comment]
Now part of Share personal data on the GOV.UK issues backlog. https://github.com/alphagov/govuk-design-system-backlog/issues/93
