### ISSUE TITLE
HMRC internal header

### ISSUE THREAD

**Issue by mikeash82** [hmrc/design-patterns#155]
# HMRC internal header

# For all internal services

## Overview
This header helps internal users easily differentiate internal services from public facing external ones. It improves the identity of HMRC internal services and increases the users confidence that they will not be sharing internal information to the public.

![image](https://user-images.githubusercontent.com/34244307/45742438-e64b3100-bbf1-11e8-8558-47680f6c108b.png)

## Is it useful and unique?
It is useful as it will be used by all internal services. It has already been used by 3 internal services.
It is unique as it is the only HMRC specific header available. and it will only be used on HMRC internal services.

## Other components or patterns you've tried
We initially tried using the GDS black background for the header with the HMRC logo but it did not give enough confidence to internal users that they were not on a public facing service.

![image](https://user-images.githubusercontent.com/34244307/45741954-b9e2e500-bbf0-11e8-97bd-89ba817e6b9a.png)

## Research on this pattern
Research on an internal service showed that the new HMRC internal header radically raised awareness that the user wasn't on a public facing GOV.UK service.

**Comment by daviddotto** [comment]
We've been looking for something exactly like this for our service, we've been testing a modified version of the GOV.UK header (the version you tried initially) so I'm glad to see an evolution of it based on more research, we'll update ours to match.
I'll report back if we gain any more insights.

**Comment by benwakefield** [comment]
Its worth noting that Internal services should not be using the GOV crown logo or Transport font.
https://www.gov.uk/service-manual/design/services-for-government-users

This immediately creates a need for a standardised way to present an internal system.

On SDES we're working on an internal admin area and are testing with this version in our next round...
<img width="865" alt="screen shot 2018-10-08 at 10 32 39" src="https://user-images.githubusercontent.com/7381460/46601703-d4b8c300-cae5-11e8-8e70-9d7d12a4e102.png"> (note the updated font stack as per GDS guidance)

**Comment by mikeash82** [comment]
> Its worth noting that aside from the user needing to differentiate an internal HMRC system from a public facing GOV.UK service, Internal services should not be using the GOV crown logo or Transport font (if not using a GOV.UK domain)
> 
> https://www.gov.uk/service-manual/design/services-for-government-users
> 
> On SDES we're working on an internal admin area and are testing with this version in our next round...
> <img alt="screen shot 2018-10-08 at 10 32 39" width="865" src="https://user-images.githubusercontent.com/7381460/46601703-d4b8c300-cae5-11e8-8e70-9d7d12a4e102.png"> (note the updated font stack as per GDS guidance)
L

**Comment by mikeash82** [comment]
> > Its worth noting that aside from the user needing to differentiate an internal HMRC system from a public facing GOV.UK service, Internal services should not be using the GOV crown logo or Transport font (if not using a GOV.UK domain)
> > https://www.gov.uk/service-manual/design/services-for-government-users
> > On SDES we're working on an internal admin area and are testing with this version in our next round...
> > <img alt="screen shot 2018-10-08 at 10 32 39" width="865" src="https://user-images.githubusercontent.com/7381460/46601703-d4b8c300-cae5-11e8-8e70-9d7d12a4e102.png"> (note the updated font stack as per GDS guidance)
> > Great. please share any finding.

**Comment by jennifer-hodgson** [comment]
I note that DIT have just raised an issue on the GOV.UK backlog for [their equivalent of this](https://github.com/alphagov/govuk-design-system-backlog/issues/152).

**Comment by benwakefield** [comment]
We asked some questions around the design last week as part of a wider workshop with Security and Information Business Partner (S&IBP aka Data Guardians) 16 out of 16 preferred the new design. 

- makes it more distinguishable, know where you are
- Should both be different. Easier to tell apart and clearer that the system is owned by HMRC not Cabinet Office, so can be challenged. 
- Internal different to Gov.uk - let’s colleagues know they can challenge it, if they know it is HMRC owned.
- Not sure an internal system needs to look so formal, we all know we work for HMRC. 
- Some colleagues also work for different OGDs so useful to tell the difference.

<img width="960" alt="screen shot 2018-10-22 at 11 18 37" src="https://user-images.githubusercontent.com/7381460/47289353-3c950080-d5f2-11e8-82a5-d8fa428882c8.png">

**Comment by benwakefield** [comment]
We asked some questions around the design last week as part of a wider workshop with Security and Information Business Partner (S&IBP aka Data Guardians) 16 out of 16 preferred the new design. 

- makes it more distinguishable, know where you are
- Should both be different. Easier to tell apart and clearer that the system is owned by HMRC not Cabinet Office, so can be challenged. 
- Internal different to Gov.uk - let’s colleagues know they can challenge it, if they know it is HMRC owned.
- Not sure an internal system needs to look so formal, we all know we work for HMRC. 
- Some colleagues also work for different OGDs so useful to tell the difference.

<img width="960" alt="screen shot 2018-10-22 at 11 18 37" src="https://user-images.githubusercontent.com/7381460/47289353-3c950080-d5f2-11e8-82a5-d8fa428882c8.png">

**Comment by mikeash82** [comment]
Upstreamed to the GOV.UK issues backlog https://github.com/alphagov/govuk-design-system-backlog/issues/152

**Comment by sophiefriell** [comment]
We received some accessibility feedback this week around this component from a **low vision analyst**. The usability issue was that the service name many not be noticed as a link by users. The suggestion to improve this was to add a hover state over the service name to indicate this is a link. The wider GOV.UK design system actually does something similar (attached).
<img width="823" alt="Screenshot 2024-03-15 at 10 51 45" src="https://github.com/hmrc/design-patterns/assets/103635012/c318cc38-efaa-4471-9a21-96f5cdc50250">
