### ISSUE TITLE
Back Navigation

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#16]
# Description
Back buttons and links

# Hackpad Discussion
https://designpatterns.hackpad.com/Back-buttons-and-links-hsdYethVO6s

**Comment by stevenaproctor** [comment]
@gavinwye More information is in the service manual on the question pages. I think it was added 26 September. https://www.gov.uk/service-manual/design/question-pages#back-link

**Comment by gavinwye** [comment]
this is in the service manual
