### ISSUE TITLE
International addresses where the postcode is used as a 'known fact'

### ISSUE THREAD

**Issue by vickytnz** [hmrc/design-patterns#160]
# International addresses where the postcode is used as a 'known fact'

# BSP Parcels

## Overview
We have a number of technical requirements for international addresses:
- the backend expects addresses in a format that is different from the GOV.UK recommended patterns. The pattern we have to use is:
   - Address line 1 
   - Address line 2
   -  Address line 3 (optional)
   -  Address line 4 (optional)
- we have to also collect a postcode as a 'known fact'. 63 countries don't have them, but we have to at least know which field the postcode should be in. Some other services have managed to not have this used as a known fact, but we can't.

We've found that just showing the fields to international users doesn't work.

This example is a first pass on what could be done to make this work. It's based on the assumption that:

1. Most international addresses don't need four lines
2. Users that need these extra fields will be used to this

This therefore hides the optional fields at first and shows a separate page to users that need the extra fields. This allows for more tailored content about what line 2 should be.
![image](https://user-images.githubusercontent.com/1223264/48011417-924fc980-e117-11e8-9c92-03233a5ff1b0.png)

## Is it useful and unique?

This is an extension of the address pattern.
It is useful for situations were users need to put in an international address and where the postcode is required for security reasons.  

This pattern should not be used when it doesn't matter what line a postcode is in. Other services have a simpler pattern of just asking for 5 address lines. 

## Other components or patterns you've tried

The version that's common to ETMP patterns caused problems in usability testing with international users (see 'research on this pattern')

![image](https://user-images.githubusercontent.com/1223264/48011536-da6eec00-e117-11e8-9f8a-b2a1e704c632.png)

## Research on this pattern

We've done testing on the earlier version of the pattern with:
- 5 users in the USA
- 5 French-native language users in France

Some US users expected to put something in line 4, not line 2.
French users only put in an address line and the postcode (not the town), so got an error when they tried to submit. They still didn't put a town in address line 2, but put in a different address or even random characters.

We haven't tested with any people yet whose countries don't have postcodes.

**Comment by stevenaproctor** [comment]
Would it be possible to ask for the country first?

If they are a country with a postal code, make it required. If they are not a country with a postal code, do not show the field.

**Comment by vickytnz** [comment]
This has led me to something else: at present there doesn't seem to be a definitive list of which countries don't have postcodes.

References I have found so far by asking around are:

- http://www.upu.int/uploads/tx_sbdownloader/manualAddressingKnowledgeCentreGeneralIssuesEn_01.pdf - UPU list of all member countries. They also have ways to see formats for all their member countries at http://www.upu.int/en/activities/addressing/postal-addressing-systems-in-member-countries.html 
- https://www.loqate.com/en-gb/address-verification/international-address-formats/ has a way to check all formats
- an informal list that someone recommended to me http://www.mapanet.eu/en/resources/Postal-Format.asp 
- another list, but with regexes https://www.grcdi.nl/gsb/world%20postal%20code%20formats.html
- a list put on github as json https://gist.github.com/bradydan/e172c3f99e211e6e47ad84f08f83dfe3  

There are also quirks such as Eirecodes (house level rather than street level), and Hong Kong having one code since the country is so small. 

Universal Postal Union has a list but only for their countries (not every country is in the UPU) 

Other references:
- Schema.org on postal addresses https://schema.org/PostalAddress
- ISO 19160 standard for address information https://www.iso.org/standard/64242.html and https://www.iso.org/obp/ui/#iso:std:iso:19160:-4:ed-1:v1:en

**Comment by jennifer-hodgson** [comment]
Thanks for this, @vickytnz. I wonder, are you aware of other services that share the same need as regards postcode as a "known fact"?

**Comment by HelenFH** [comment]
This is something that may be relevant to us in Exports. We have many parties involved where we ask for details - preferably the EORI number, but they will not all necessarily have one and so the address has to be entered instead. So far we are using the standard pattern (4 lines plus postcode and country) however, I have previously raised in a crit that this will not suit all countries. I was advised at the time that we should just use this pattern anyway and make the postcode field non-compulsory but it will be interesting for us to user test this when non member states are involved and unlikely to have a EORI.

**Comment by stevenaproctor** [comment]
@HelenFH Thanks for the comment. There is a definite need for an international address pattern too. See the address issue on the GOV.UK Design System backlog.
https://github.com/alphagov/govuk-design-system-backlog/issues/31

**Comment by adevaney** [comment]
@stevenaproctor  - just further info on what was mentioned on the design system call today. For MTD we are migrating addresses from VAT Main Frame (VMF) to ETMP as users sign up for MTD. All overseas traders have their address defaulted to a HMRC office in Aberdeen in VMF and this is the record that is being migrated to ETMP. Might be worth considering if using postcode as a known fact as it will be the Aberdeen address that is stored and validated against.

**Comment by iancuddy** [comment]
In our research for Overseas Agents, a user suggested in Ireland a third of properties don't have postcodes; for this reason we didn't include it our international address entry screen.
[https://www.prototypes.tax.service.gov.uk/agent-onboarding-prototype/sprint-future/overseas-agents/main-trading-address ](https://www.prototypes.tax.service.gov.uk/agent-onboarding-prototype/sprint-future/overseas-agents/main-trading-address )

We have Confluence page explaining how these fields interact with ETMP (this is specific to Agent services).
https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=145000402#ValidationinOverseasAgentsApplication&Subscriptionjourneys-Yourmaintradingaddress

**Comment by stevenaproctor** [comment]
@vickytnz We had a talk in the working group on 18 January 2019 about postcode as a known fact.

Postcode can be used as a known fact now but not on its own. We ask for more than one known fact to make sure the information we retrieve is correct.

In terms of useful and unique, it may be useful and unique to use postcode on its own but the lack of certainty it provides means it cannot be a pattern.

During the discussion, there were some questions about using something that not every user would have. What would happen in those situations?

There were a lot of comments about international addresses, including:

- using an international postcode lookup
- problems validating postal and zip codes
- leaving out postal code from overseas addresses in agents because there was too many countries that did not have postcode – people could enter it in another field if they wanted to
- what label to use on the postcode field

I am closing the issue. If you need any more information let me know.
