### ISSUE TITLE
Gender and Sex

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#17]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22466167/562c8afe-e7bf-11e6-8c68-809472ea1fa4.png)

# GOV.UK Pattern

https://www.gov.uk/service-manual/user-centred-design/resources/patterns/gender-and-sex.html

**Comment by stevenaproctor** [comment]
@gavinwye The pattern in the service manual is different. But it is definitely a GOV.UK pattern.

**Comment by gavinwye** [comment]
this is a gov.uk pattern so closing it
