### ISSUE TITLE
Interstitial

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#18]
# Description
Interstitial page

# Screenshot
![unable to confirm your identity online - confirm your identity](https://cloud.githubusercontent.com/assets/2305016/22466249/62b36890-e7b7-11e6-90a3-9c405e6a69d4.png)

**Comment by stevenaproctor** [comment]
@gavinwye #18, #41, #52, #57 and #98 are similar. They are pages of content. Could this be a single pattern?

**Comment by gavinwye** [comment]
closing this as it's a sign post #98
