### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#19]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22466263/d11d9e4c-e7bf-11e6-94d5-f1a7fad15e5e.png)

**Comment by stevenaproctor** [comment]
@gavinwye This should be a GOV.UK pattern. Other services use Government Gateway. The page is not the same as the screenshot (at least in the personal tax account).

See https://www.tax.service.gov.uk/gg/sign-in?continue=%2Fpersonal-account%2Fdo-uplift%3FredirectUrl%3D%252Fpersonal-account&accountType=individual&origin=PERTAX

**Comment by elenecid** [comment]
I agree that it should be a gov.uk pattern.

**Comment by stevenaproctor** [comment]
This issue was closed because it is a separate microservice that all services use. It does not need to be documented.
