### ISSUE TITLE
Select options 

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#2]
## Description
Used to select from a range of options 

## Screen shot
![image](https://cloud.githubusercontent.com/assets/868772/22253847/eda7b27a-e24a-11e6-9740-fa33c5f69ea7.png)

## Linked resources and patterns
This pattern uses the radio buttons described on [GOV.UK elements](https://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons).

## Research
We need usability research for this pattern

## Design rational
To do

## Pattern makeup
1. Question
2. Radio button options
3. Continue button

## Questions
Should this pattern be used if there is only one option?
Should there be a maximum number of options for patterns like these?

## Known issues
We can currently update Assets Frontend so we can't update the radio buttons to reflect the new buttons provided by GDS.

**Comment by rpowis** [comment]
> We can currently update Assets Frontend so we can't update the radio buttons to reflect the new buttons provided by GDS.

The [multiple choice radio buttons from Elements](http://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons) are now available in assets-frontend.

**Comment by gavinwye** [comment]
this is in elements and should not have an HMRC version
