### ISSUE TITLE
Email sent confirmation

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#20]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22466303/f8b5a404-e7bf-11e6-9a1b-2208acf07282.png)

# GOV.UK Guidance

There's guidance on this here https://www.gov.uk/service-manual/user-centred-
design/resources/patterns/email-confirmation-loop.html

**Comment by stevenaproctor** [comment]
@gavinwye This feels like something that should be in the email confirmation loop section of the service manual.

**Comment by rpowis** [comment]
Agreed. This should definitely be a final step in a multi-step pattern, not a pattern in its own right.

**Comment by stevenaproctor** [comment]
This issue has been closed because it should be part of an email confirmation loop in the GOV.UK Design System.
