### ISSUE TITLE
Info & Guidance

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#22]
# Description
Info & Guidance

# Screenshot
![employment intermediaries-report template - publications - gov uk 20160926](https://cloud.githubusercontent.com/assets/2305016/22466347/c38d1a3a-e7b7-11e6-95a0-f0438da85d70.png)

# Service Manual
https://www.gov.uk/service-manual/design/help-text

**Comment by stevenaproctor** [comment]
@gavinwye This is a GOV.UK page. Are people putting this inside a service?

**Comment by gavinwye** [comment]
closing this as it's a not controlled by HMRC and belongs to GOV.UK
