### ISSUE TITLE
Date Input

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#23]
# Description
Date Input

# Screenshot
![file your company accounts and tax online](https://cloud.githubusercontent.com/assets/2305016/22466392/f808491a-e7b7-11e6-873e-cafcae624dd6.png)

# Service Manual
https://www.gov.uk/service-manual/design/dates

**Comment by stevenaproctor** [comment]
@gavinwye This is a GOV.UK pattern similar to #35.

**Comment by gavinwye** [comment]
this is in the service manual and elements and not something that we should be doing
