### ISSUE TITLE
Alpha banner

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#24]
# Description
Alpha

# Screenshot
![pla - welcome](https://cloud.githubusercontent.com/assets/2305016/22466440/2afb9886-e7b8-11e6-851a-1a959707ad8c.png)

# Service Manual
https://www.gov.uk/service-manual/design/alpha-and-beta-phase-banners

**Comment by gavinwye** [comment]
We need to update this taking account of the new GOV.UK alpha banner

**Comment by stevenaproctor** [comment]
@gavinwye GOV.UK pattern.

**Comment by stevenaproctor** [comment]
Closed as it is part of the GOV.UK design system backlog.
