### ISSUE TITLE
Which country?

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#27]
# Screenshots

**Example 1**
![image](https://cloud.githubusercontent.com/assets/1752124/22466405/5eaeb5c0-e7c0-11e6-8da8-c13eac3bda3f.png)

**Example 2**
![image](https://cloud.githubusercontent.com/assets/1752124/22466437/8aa131e4-e7c0-11e6-9ff2-8285500f2856.png)

**Comment by stevenaproctor** [comment]
@gavinwye Is this a specific pattern? Or is it just a set of radio buttons and a text field?

The radios should be vertically stacked because there is more than 2 of them. See http://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons

**Comment by rpowis** [comment]
@stevenaproctor Those are separate screenshots. I've added headings to (hopefully) make it clearer.

It's more of a "Country picker" component IMO

**Comment by stevenaproctor** [comment]
@rpowis OK. Is it not superseded by the GOV.UK autocomplete or a standard set of radio buttons?

**Comment by russellthorn** [comment]
Although created long before the new radio buttons Register to vote have this pattern - https://www.registertovote.service.gov.uk/register-to-vote/country-of-residence?_ga=2.258443402.1688332797.1511342022-331215250.1510583990

**Comment by russellthorn** [comment]
But is it a pattern or just a fairly simple set of radio buttons?

**Comment by russellthorn** [comment]
Country finder pattern from Defra - https://defradigital.blog.gov.uk/2017/11/22/putting-the-service-toolkit-to-work/

**Comment by gavinwye** [comment]
GDS are doing this so we should not be. But speaking to @timpaul the work on this has been paused so if we have services that need this we can potentially pick up the work that GDS have done and build on it with a view of contributing this back.

**Comment by stevenaproctor** [comment]
This issue has been closed because it will be part of the GOV.UK Design System. Possibly as part of the accessible autocomplete. Otherwise, it is a text field or a set of radio buttons.
