### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#29]
# Description
Service Unavailable

# Screenshot
![service is unavailable due to maintenance](https://cloud.githubusercontent.com/assets/2305016/22467594/2b3bff20-e7bd-11e6-8889-e22ecef82511.png)

# Example
http://hmrc-shutter-pages.herokuapp.com/suggestions/
> Login details in Confluence `Pages > Service design> Prototypes of our services`

# Digital Service Standard
This is covered in point 11 of the service standards "11. Make a plan for being offline" but there are no patterns for this.

https://www.gov.uk/service-manual/service-standard/make-a-plan-for-being-offline

**Comment by alex16wake** [comment]
Example of a similar page used in SCRS

![image](https://user-images.githubusercontent.com/24815473/28578320-4ea6484e-7151-11e7-9a9f-389f67d2d8e4.png)

**Comment by stevenaproctor** [comment]
@gavinwye All shutter pages and technical problem pages need to be standardised. There are no patterns in the service manual, so we could suggest ours for the design system.

**Comment by gavinwye** [comment]
@stevenaproctor yes we have Shutter pages for this #103 I won't close this yet as we possibly should take note of @alex16wake's work.

**Comment by gavinwye** [comment]
closing this as it's covered by shutter pages
