### ISSUE TITLE
Spinner UI control

### ISSUE THREAD

**Issue by russell-hmrc** [hmrc/design-patterns#3]
## Description

A spinner (AKA stepper) control is a two-part button used to increase or decrease a value in increments.

## Screenshot

![image](https://cloud.githubusercontent.com/assets/20208956/22300039/1a3f67be-e31e-11e6-94e5-31dd5652965a.png)

## Linked resources and patterns

(https://developer.apple.com/ios/human-interface-guidelines/ui-controls/steppers/)

(naming convention study)
(http://uxfindings.blogspot.co.uk/2014/06/is-numeric-spinner-best-name-for-this.html)

https://blog.mobiscroll.com/slider-segmented-stepper-and-progress-mobiscroll-2-17-released/

## Research

(pending)

**Comment by gavinwye** [comment]
I think this is probably an component rather than a pattern

**Comment by stevenaproctor** [comment]
@gavinwye Is this a component?

**Comment by rpowis** [comment]
@stevenaproctor I'd say so.

**Comment by gavinwye** [comment]
Comments from London

- As a first impression: it looks more like a component. 
- Is it a unique need? How is currently done (an example)? Drop down menu? 
- How often is it used across services? 
- What’s the benefit of it? and the need?
- Concerns about design.

**Comment by gavinwye** [comment]
@adamliptrot-oc @russell-hmrc could you update this issue with detail around where it's used and UR 
When we come to document this we need to be clear about when it should be used
We need to figure out if this should be a component in its own right
At the moment we think this is useful and unique

**Comment by russell-hmrc** [comment]
Some UR and notes can be found here
[https://confluence.tools.tax.service.gov.uk/display/SSTTP/Design+patterns](url)
