### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#30]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22466627/76b471fe-e7c1-11e6-8af7-28cfb653f1d1.png)

# GOV.UK Element

https://govuk-elements.herokuapp.com/form-elements/#form-checkboxes

**Comment by stevenaproctor** [comment]
@gavinwye GOV.UK pattern. This is a component from elements.

**Comment by gavinwye** [comment]
closing this as it's a style from elements
