### ISSUE TITLE
Success

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#34]
# Description
Success

# Screenshot
![pla - welcome](https://cloud.githubusercontent.com/assets/2305016/22466758/a49fe2cc-e7b9-11e6-9261-ddd99616216e.png)

# Service Manual
https://www.gov.uk/service-manual/design/confirmation-pages

**Comment by stevenaproctor** [comment]
@gavinwye This is a GOV.UK pattern. It is a confirmation page.

**Comment by gavinwye** [comment]
closing this as it's in the service manual
