### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#35]
# Description
Date

# Screenshot
![please enter the date the property was sold or given away](https://cloud.githubusercontent.com/assets/2305016/22466803/d105681e-e7b9-11e6-9cd2-142fc19dc1b0.png)

# Service Manual
https://www.gov.uk/service-manual/design/dates

**Comment by stevenaproctor** [comment]
@gavinwye This is a GOV.UK pattern.

**Comment by gavinwye** [comment]
this is a gov.uk this that is in the service manual and elements
