### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#36]
# Description
Navigation

# Screenshot
![paye for employers messages - business tax account - gov uk 2](https://cloud.githubusercontent.com/assets/2305016/22466980/a6e6173a-e7ba-11e6-9349-fff2112f1e64.png)

# Research Questions
Is this a pattern? Isn't this a whole bunch of patterns? Or a dashboard?

**Comment by stevenaproctor** [comment]
@gavinwye Is it worth renaming this "Business tax account navigation"?

**Comment by rpowis** [comment]
@stevenaproctor No. Patterns shouldn't be service specific.

i.e. The PTA navigation is actually "Account menu"

**Comment by adamliptrot-oc** [comment]
This feels more like a "What do you want to do?" kind of page

**Comment by gavinwye** [comment]
This kind of navigation isn't really a thing.

We have:
- navigation in PTA header
- tiles in PTA
- secondary navigation
- primary navigation #82 
- breadcrumbs
- pagination
- backlinks 
- possible more...

It's probably a group of things that can be defined across government.

**Propose closing this issue and creating issues for the above components.**

**Comment by adamliptrot-oc** [comment]
Added an issue for Tiles / Cards #137

**Comment by stevenaproctor** [comment]
The issue was closed because there is not enough information. There could be an issue for specific navigation for different accounts.
