### ISSUE TITLE
Change your address

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#37]
# Description
Address

# Screenshot
![https---bbsi-gross bbsi-prototype herokuapp com-service-pta-ms-address-update-address html hmrc prototype kit 20160928](https://cloud.githubusercontent.com/assets/2305016/22466867/2245c732-e7ba-11e6-917e-de26b95f2c9a.png)

# Service Manual
https://www.gov.uk/service-manual/design/addresses

**Comment by gavinwye** [comment]
Update your address patterns/components from the personal tax account live service.

Accessed via the "update your address link

<img width="998" alt="screenshot 2017-02-16 11 56 18" src="https://cloud.githubusercontent.com/assets/868772/23021940/6ac87106-f446-11e6-8986-ac610eca46d9.png">

<img width="987" alt="screenshot 2017-02-16 11 51 49" src="https://cloud.githubusercontent.com/assets/868772/23020356/9806a212-f43e-11e6-8ed0-314303d9b75f.png">

<img width="1001" alt="screenshot 2017-02-16 11 52 44" src="https://cloud.githubusercontent.com/assets/868772/23020366/a2c06b0c-f43e-11e6-8aca-7b0d27e3b7a7.png">

**Comment by gordonmcmullan** [comment]
## User research
Principal place of business
version 28		
18 Jan 2017 
Mobile user needed more guidance about what to put here as their work takes them all over the country

**Comment by gordonmcmullan** [comment]
## User research

Principal place of business	
version 30	
01 Feb 2017  
Users much preferred this address pattern when selecting a new address, so long as it's not a very long list.
User points out that this might be difficult to use if there's a lot of addresses (gives example of apartments)
Action: Check if address for office blocks will get complicated

**Comment by gordonmcmullan** [comment]
## User research

Principal place of business	
Version 31	
08 Feb 2017  
Users much preferred this address pattern when selecting a new address, so long as it's not a very long list. (Finding from later in the journey - users did their business at their registered office)
Action: Check if address for office blocks will get complicated (as with v30)

**Comment by gordonmcmullan** [comment]
Director correspondence address	
Version 28	
18 Jan 2017 
No issues on mobile

**Comment by gordonmcmullan** [comment]
Director correspondence address	
Version 30	
01 Feb 2017 
No issues

**Comment by gordonmcmullan** [comment]
Director correspondence address	
Version 31	
08 Feb 2017  
Users missed the "find address" step	
ITERATE
Action: Make it more obvious to me that "Find address" is a required action TO DO

**Comment by gordonmcmullan** [comment]
Director Correspondence address	 
Version 32	
15 Feb 2017 
One user would have liked all addresses he had entered to be displayed at this point.  He had entered 2 addresses prior to this page.	
COMPLETE
Action: check if this is prototype only behaviour
Action: Define and implement address pre-pop solution

**Comment by gordonmcmullan** [comment]
Director home address	
Version 28	
18 Jan 2017 
One mobile user thought the warning icon around the public record, meant there was an error on the page	
Design to look at use of the icon
ITERATE
Action: Public Record USER RESEARCH

**Comment by gordonmcmullan** [comment]
Company registered address	
Version 30	
01 Feb 2017  
Users missed that they had to click on "find address"
ITERATE
Iterate on design to make it clear that "find address" is a required action rather than some sort of help tool.
Action: Make it more obvious to me that "Find address" is a required action

**Comment by gordonmcmullan** [comment]
Company registered address	
Version 31	
08 Feb 2017  
Users missed that they had to click on "find address"
ITERATE
As with v30.
Action: Make it more obvious to me that "Find address" is a required action

**Comment by gordonmcmullan** [comment]
Company registered address	 
Version 35	
08 Mar 2017 
Couple of users entered full 1st line of address in house number field	
MONITOR

**Comment by gordonmcmullan** [comment]
Company registered address	 
Version 37
22 Mar 2017 
1 user entered full address in first field	
MONITOR

**Comment by gordonmcmullan** [comment]
Company registered address	
Version 36	 	
Half users missed "Find Address"	
MONITOR
Action: investigate options 
21 Mar 2017 We're doing investigations into how the address pages are being used in the live service. There isn't much we can do at this point. Changing to monitor.

**Comment by stevenaproctor** [comment]
@gavinwye Is this just for change your address? Could it be to find or add your address too?

I have seen a handful of postcode look ups. They need to be standardised.

**Comment by gavinwye** [comment]
@stevenaproctor I think everything relating to address should be standardised under one single address pattern in #96

**Comment by stevenaproctor** [comment]
This issue was closed because it should be part of #96.
