### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#38]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22466866/839d7ab8-e7c2-11e6-8784-8390bbc66056.png)

# Hackpad Discussion

https://designpatterns.hackpad.com/Task-lists-PqlWl4PhoYV

**Comment by gavinwye** [comment]
Task list used in Anti Money Laundering Service.
This is an early prototype so look at the production service for a more up-to-date version
![image](https://user-images.githubusercontent.com/868772/27219576-1459b2a2-527a-11e7-8179-e5be1768d71e.png)

**Comment by stevenaproctor** [comment]
@gavinwye GOV.UK pattern? https://www.gov.uk/service-manual/design/task-list-pages-beta

Or should we be adding to the GOV.UK pattern and offering alternatives? I have seen at least 2 or 3 different versions.

**Comment by vickytnz** [comment]
The pattern used in AWRS and IHT is this
![screen shot 2017-12-06 at 11 41 28](https://user-images.githubusercontent.com/1223264/33660224-09aa7ff6-da7b-11e7-8bde-46e4589f7ca8.png)

**Comment by vickytnz** [comment]
also better showing of progress for AMLS 
![screen shot 2017-12-06 at 11 49 08](https://user-images.githubusercontent.com/1223264/33660403-8663e1a4-da7b-11e7-8943-22a83ef0c12c.png)

**Comment by stevenaproctor** [comment]
This issue has been closed because this will be in the GOV.UK Design System. There is no reason why our task lists should be different to other departments.
