### ISSUE TITLE
Tax year

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#39]
# Description
Tax year

# Screenshot
![paac](https://cloud.githubusercontent.com/assets/2305016/22466906/53de5d86-e7ba-11e6-8dda-5ad8a1eb3ca1.png)

**Comment by stevenaproctor** [comment]
@gavinwye This is a GOV.UK pattern. The content is lifted from the content style guide. See https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#dates

I have seen people not understand what the tax year is, so we should use the dates 6 April to 5 April when needed.

**Comment by gavinwye** [comment]
this should point to the content in the GOV.UK style guide

**Comment by gavinwye** [comment]
I've reopened this so that it goes in the backlog and can get added to the design system

**Comment by stevenaproctor** [comment]
The issue was closed because it is covered in the GOV.UK content style guide – see https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#dates
