### ISSUE TITLE
HMRC header

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#4]
This will more than likely be a child of the [GOV.UK header](https://www.gov.uk/service-manual/design/add-the-govuk-header-and-footer)

## To Do
- [ ] content review of the pattern description
- [ ] code review of example markup
- [ ] assessability review of examples
- [ ] add a skip link to the header examples
- [ ] add `role="main"` to the `main` element

## Screenshots
These are the screenshots that are live today collected here for reference.

#### Personal tax account 
![personal-tax-account-header](https://cloud.githubusercontent.com/assets/868772/23172067/7d128efa-f84c-11e6-874f-44c8c67fba91.png)

#### Business tax account 
![bussiness-tax-account-header](https://cloud.githubusercontent.com/assets/868772/23172076/861160da-f84c-11e6-9d54-cbc7a4a534a2.png)

#### Personal tax account 
![personal-tax-account-header-mobile](https://cloud.githubusercontent.com/assets/868772/23172088/8dedbd58-f84c-11e6-8b91-be3c00ed5b6f.png)

#### Business tax account 
![business-tax-account-header-mobile](https://cloud.githubusercontent.com/assets/868772/23172087/8dec8b9a-f84c-11e6-9f09-9c0ee9159d12.png)

**Comment by vickytnz** [comment]
Is there a reason that the version that's on the patterns doesn't have the sign out link top right?

**Comment by gavinwye** [comment]
@vickytnz no that's a bug it should have a sign out link. I'll get it updated.

**Comment by gavinwye** [comment]
@vickytnz the page has now been updated https://hmrc-design-patterns.herokuapp.com/patterns/header

**Comment by gavinwye** [comment]
See the latest work on this pattern in the [design pattern library](https://hmrc-design-patterns.herokuapp.com/patterns/header).

**Comment by gavinwye** [comment]
There is a pull request open for this against Assets Frontend https://github.com/hmrc/assets-frontend/pull/819

**Comment by stevenaproctor** [comment]
@jennifer-hodgson This is the HMRC-specific extras to the GOV.UK header. Probably a good idea to rename it HMRC header. What do you think?

**Comment by mikeash82** [comment]
Moved to [site header](https://github.com/alphagov/govuk-design-system-backlog/issues/97) on GOV.UK issues backlog

**Comment by terrysimpson99** [comment]
The text says "The sign out link should be inside the GOV.UK header, on the right hand side." and then shows an image with no sign out link.

Is there an error in the image?

**Comment by IxDradge** [comment]
Hi, this pattern seems to have a bug in it, when I apply the code the blue line under the header wraps awkwardly. I used the code:
```
{{ hmrcHeader({
  "serviceName": "Service Name",
  "serviceUrl" : "/",
  "phaseBanner" : true,
  "signOutHref" : "?sign-out"
}) }}
```
![image](https://user-images.githubusercontent.com/87651135/141100910-d8e80dfa-7713-4aaa-bc56-f4e17a8f9cad.png)

**Comment by IxDradge** [comment]
You can see the bug in the HMRC design system web page - 
![image](https://user-images.githubusercontent.com/87651135/141101138-0b89b286-a5e0-42bc-8406-a4e3593634b6.png)

**Comment by IxDradge** [comment]
Ah got you, thanks. All working now.

**Comment by IxDradge** [comment]
Just one problem, I now can't over-write the service name on individual pages. The service name is set to what ever I call it in the layout.html file. I'd like to be able to over-write it on individual pages using this snippet - 
```
{% set serviceName %}
Business tax account
{% endset%}
```
Any ideas? Thanks again.

**Comment by timsb** [comment]
In the prototype kit this can be done by either creating multiple layout files or in each individual page view overwriting/redefining the header block.

**Comment by IxDradge** [comment]
Gotcha, many thanks

**Comment by samijanderson** [comment]
Hello, I know this pattern is specifically about the sign out link in the header, but I wondered if there are any other standards as to when we should mention that a user will be signed out.

For example, we have a page that tells the user they're already registered to use our service, after they attempt to register with a different Government Gateway user ID:

<img width="187" height="95" alt="Image" src="https://github.com/user-attachments/assets/c3d27b52-1f0e-4506-a052-73e8f0fe40b6" />

In this case, if they select the 'Sign in...' link, they'll be signed out in order to sign in again. However, we're not telling the user that they'll be signed out, as this feels like it'd be quite clunky to convey in this context (and the main action they need to complete is signing in again to use the right Government Gateway user ID).

I was going to leave this as it is, but thought it'd be useful to check in on here.

Thanks

**Comment by Jon-Rowe-HMRC** [comment]
Hi @samijanderson 

The only other standard I can think of regarding when we should mention that a user will be signed out is the service timeout pattern: https://design.tax.service.gov.uk/hmrc-design-patterns/service-timeout/

Most of the development for authentication is now centred around One Login, and from a pattern perspective, we are currently taking their lead. Here is their documentation:
https://www.sign-in.service.gov.uk/documentation/design-recommendations/let-users-navigate-sign-out
https://github.com/govuk-one-login/service-header?tab=readme-ov-file#a-header-for-services-using-govuk-one-login

We are in the process of modifying the sign out pattern (https://design.tax.service.gov.uk/hmrc-design-patterns/sign-out/) to match One Login more closely, but these will be relatively minor aesthetic changes.

**Comment by amywallishmrc** [comment]
Hi - are you aware that the sign out link in the banner does not show as underlined when hovered over in Windows high contrast mode? All other links are underlined on hover, and it works in 'normal' contrast mode.

https://github.com/user-attachments/assets/49115c0b-a0b7-4002-a977-8803e6946b89

**Comment by timsb** [comment]
Thanks @amywallishmrc! We hadn't spotted this. I've added it to our backlog
