### ISSUE TITLE
2-factor authentication

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#40]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22466905/b3557792-e7c2-11e6-85f8-9c318a654bcc.png)

# Hackpad Discussion

https://designpatterns.hackpad.com/Phone-numbers-9Gnnfam9Aqr

**Comment by gavinwye** [comment]
## Questions for this pattern
1. Why are we not detecting that the phone number is a UK phone number from the input? According to the documentation on [Hackpad](https://designpatterns.hackpad.com/Phone-numbers-9Gnnfam9Aqr) UK mobile phone numbers are in this format 07700 900000 to 900999.
2. Is the help text above the phone number input field working? Do users know at the stage that they are inputting their phone number that they will always have access to it?
3. What is the impact of clicking the I can't do this right now link?

**Comment by stevenaproctor** [comment]
@gavinwye Is this a pattern? The screenshot would suggest it is only for two-factor authentication.

**Comment by stevenaproctor** [comment]
This issue was closed because it is a separate microservice that all services use. It does not need to be documented.
