### ISSUE TITLE
End

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#41]
# Description
End

# Screenshot
![you have no tax to pay](https://cloud.githubusercontent.com/assets/2305016/22466949/875c684c-e7ba-11e6-9ef9-51668ebc44d3.png)

# Research Questions
This seems to be a pattern around "what do we do when the user can't use the service to perform the action they want to perform?"

**Comment by stevenaproctor** [comment]
@gavinwye #18, #41, #52, #57 and #98 are similar. They are pages of content. Could this be a single pattern?

**Comment by gavinwye** [comment]
not useful or unique
