### ISSUE TITLE
National Insurance Number

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#42]
# Screenshots

![image](https://cloud.githubusercontent.com/assets/1752124/22466933/dc2c6bee-e7c2-11e6-92e8-64bb34e97551.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22466948/e82c4c20-e7c2-11e6-9c46-84b787ac43bc.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22466958/ef9be2b8-e7c2-11e6-99f9-5a547487cfc4.png)

# GOV.UK Pattern

https://www.gov.uk/service-manual/user-centred-design/resources/patterns/national-insurance-number.html

**Comment by alex16wake** [comment]
![image](https://user-images.githubusercontent.com/24815473/28575532-18c2c4a8-7149-11e7-8003-48ad2821515f.png)

**Comment by gavinwye** [comment]
## Error messages
- The dummy number should always be QQ123456C because it is definitely not someone's number.

**Comment by stevenaproctor** [comment]
@gavinwye Is this a pattern? Or is it a standard question with the National Insurance number component?

**Comment by stevenaproctor** [comment]
This issue was closed because it will be part of the GOV.UK Design System.
