### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#44]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22467024/377da4b8-e7c3-11e6-99a9-84b0ecac17d7.png)

**Comment by fordie** [comment]
Messages  / inbox in Digital contact

![screenshot from 2018-01-11 14-31-27](https://user-images.githubusercontent.com/494985/35436880-0d50513c-0288-11e8-9113-17a0a4994e0f.png)

**Comment by fordie** [comment]
VOA CCA Messages tab
![image](https://user-images.githubusercontent.com/494985/35437173-2e1cd268-0289-11e8-9427-0c53cdc7e7cd.png)

**Comment by jennifer-hodgson** [comment]
Adding in new examples following DS WG discussion. This is from "Your messages" on PTA.

![your messages](https://user-images.githubusercontent.com/29708171/35518772-61a046be-050a-11e8-913d-83614243cda4.png)

**Comment by jennifer-hodgson** [comment]
@rpowis - is the first screenshot you posted above from BTA?

**Comment by gordonmcmullan** [comment]
Discussion Summary from hackday

![img_20180312_140012](https://user-images.githubusercontent.com/234825/37339799-c7562080-26b3-11e8-8340-29af58753556.jpg)
![img_20180312_140016](https://user-images.githubusercontent.com/234825/37339805-cc65834a-26b3-11e8-9dbf-685c86052632.jpg)

**Comment by stevenaproctor** [comment]
GOV.UK pattern. No issue on the Design System backlog.

**Comment by mikeash82** [comment]
Upstreamed to the GOV.UK issues backlog https://github.com/alphagov/govuk-design-system-backlog/issues/168
