### ISSUE TITLE
Steps

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#45]
# Description
Steps

# Screenshot
![please enter the date the property was sold or given away](https://cloud.githubusercontent.com/assets/2305016/22467044/ed14ae88-e7ba-11e6-8156-3c28af25fbd3.png)

# Service Manual
https://www.gov.uk/service-manual/design/progress-indicators

**Comment by stevenaproctor** [comment]
@gavinwye GOV.UK pattern.

**Comment by gavinwye** [comment]
closing this as it's a GOV.UK pattern
