### ISSUE TITLE
Compare

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#47]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22467129/b0c14c9e-e7c3-11e6-80b0-846eb397f7b9.png)

**Comment by rpowis** [comment]
Explore need for this pattern

**Comment by stevenaproctor** [comment]
@gavinwye I am sure @etheya has redesigned this for the childcare calculator. Not sure if something like this is in any other service.

**Comment by gavinwye** [comment]
close this as @etheya is working on this

**Comment by etheya** [comment]
Yes you can forget this pattern as we have been working on a new solution for this.
