### ISSUE TITLE
HMRC footer

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#5]
This will most likley be a child of the GOV.UK footer

## Screenshots
These are the screenshots that are live today collected here for reference.
#### Personal tax account
![personal-tax-account-footer](https://cloud.githubusercontent.com/assets/868772/23172246/1875caba-f84d-11e6-87c6-fa0f87fd914a.png)

#### Business tax account
![bussiness-tax-account-footer](https://cloud.githubusercontent.com/assets/868772/23172247/187624c4-f84d-11e6-8a40-b4e8f6445761.png)

#### Personal tax account
![personal-tax-account-footer-mobile](https://cloud.githubusercontent.com/assets/868772/23172245/18747c46-f84d-11e6-9209-1f871f03c9ff.png)

#### Business tax account
![business-tax-account-footer-mobile](https://cloud.githubusercontent.com/assets/868772/23172248/187b94cc-f84d-11e6-8d91-40376b2c571a.png)

**Comment by gavinwye** [comment]
We need to identify why the links we have in the footer are there. We currently have:
Cookies https://www.tax.service.gov.uk/help/cookies.
Privacy policy https://www.tax.service.gov.uk/help/privacy.
Terms and conditions https://www.tax.service.gov.uk/help/terms-and-conditions.
Help using GOV.UK https://www.gov.uk/help.

The 'Help using GOV.UK' page also has links to generic GOV.UK cookies, privacy policy & terms and conditions pages. It's likely that users would assume that these pages are the same as the HMRC pages. Which is not the case.

**Comment by rpowis** [comment]
@gavinwye Pretty sure we took a steer from the footer links on https://www.gov.uk/, which are:

Help [/help](https://www.gov.uk/help)
Cookies [/help/cookies](https://www.gov.uk/help/cookies)
Contact [/contact](https://www.gov.uk/contact)
Terms and conditions [/help/terms-conditions](https://www.gov.uk/help/terms-conditions)
Rhestr o Wasanaethau Cymraeg [/cymraeg](https://www.gov.uk/cymraeg)

[Prior to that](https://web.archive.org/web/20130628090921/https://www.gov.uk/), they were:

Support https://www.gov.uk/support
Cookies https://www.gov.uk/support/cookies
Feedback https://www.gov.uk/feedback
Cymraeg https://www.gov.uk/cymraeg

**Comment by gavinwye** [comment]
This pattern is in the prototype https://hmrc-design-patterns.herokuapp.com/patterns/footer

**Comment by gavinwye** [comment]
The footer should have a link to the User Panel so people can apply to take part in user research.

**Comment by davidnearney** [comment]
The bottom link will allow us to track which users have signed up to the User Panel through a footer. 

The text should say something along the lines of "Help improve HMRC Services" - Is there is a character limit? 

I'll ask a content designer to come up with something more effective. 

https://signup.take-part-in-research.service.gov.uk/?utm_campaign=HMRCfooter&utm_source=Other&utm_medium=other&t=HMRC&id=80

**Comment by wolfendale** [comment]
Some useful statistics for the footer links:

Of the ~14 million sessions on the `tax.service.gov.uk` domain during the period 1/10/17 to 31/10/17 approximately 0.1% clicked a link in the footer. Of these, 67% clicked on the `Help` link.

One service (`business-rates-check`) has a custom link in their footer labelled `Feedback`

**Comment by jennifer-hodgson** [comment]
On the [GOV.UK Design System backlog ](https://github.com/alphagov/govuk-design-system-backlog-prototype/issues/19)- presume for future federated ambitions.

**Comment by stevenaproctor** [comment]
Totally agree. I am not sure their is a HMRC-specific footer. The Welsh language link should not be in the footer.

**Comment by jennifer-hodgson** [comment]
I wonder if this is the kind of pattern that we should design and develop and then upstream?

**Comment by stevenaproctor** [comment]
There is [site footer](https://github.com/alphagov/govuk-design-system-backlog/issues/96) on the GOV.UK Design System backlog.

**Comment by jennifer-hodgson** [comment]
Let's close it. Designers should use the GOV.UK Design System footer.
