### ISSUE TITLE
Ranges of values

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#51]
# Screenshots

![image](https://cloud.githubusercontent.com/assets/1752124/22467343/93ea6a50-e7c4-11e6-9098-03d3d7979ad4.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467361/a0ff8d1a-e7c4-11e6-9d0a-026d7c3fce7c.png)

**Comment by rpowis** [comment]
This is a content style guide thing rather than a design pattern thing

**Comment by stevenaproctor** [comment]
@gavinwye Agree with @rpowis. This is from the content style guide. Use "to" in date, number and address ranges.

**Comment by gavinwye** [comment]
closing this as it's not a pattern
