### ISSUE TITLE
Dead end

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#52]
# Description

This is what we do when we need to tell someone that they can't use a service

# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22467483/2021c3ba-e7c5-11e6-9784-0065983ee746.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467475/18ad36fa-e7c5-11e6-84cb-8623752cd01b.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467461/0d5eca02-e7c5-11e6-9026-7bf656940aa3.png)

**Comment by stevenaproctor** [comment]
@gavinwye #18, #41, #52, #57 and #98 are similar. They are pages of content. Could this be a single pattern?

**Comment by gavinwye** [comment]
closing this as it's a variant of #98
