### ISSUE TITLE
Service Closed

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#54]
# Description
Service Closed

# Screenshot
![tax credits calculator](https://cloud.githubusercontent.com/assets/2305016/22467541/f9f76404-e7bc-11e6-9264-e2a229414fbd.png)

# Example
http://hmrc-shutter-pages.herokuapp.com/suggestions/
> Login details in Confluence `Pages > Service design> Prototypes of our services`

# Digital Service Standard
This is covered in point 11 of the service standards "11. Make a plan for being offline" but there are no patterns for this.

https://www.gov.uk/service-manual/service-standard/make-a-plan-for-being-offline

**Comment by stevenaproctor** [comment]
@gavinwye Similar to #29.

**Comment by gavinwye** [comment]
closing as this is covered by shutter pages
