### ISSUE TITLE
Displaying results

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#55]
# Existing Examples

![image](https://cloud.githubusercontent.com/assets/1752124/22467610/9a6e18bc-e7c5-11e6-8922-2f50092db0a0.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467635/b23e545c-e7c5-11e6-8641-7931466eaf3f.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467652/bf78396c-e7c5-11e6-9753-beeac320646f.png)

**Comment by rpowis** [comment]
Would this be better split in two? 
1. search results 
2. calculated results

**Comment by gavinwye** [comment]
this encompasses 
- search results
- displaying results to a user

**Comment by stevenaproctor** [comment]
The issue was closed because it how we display search and calculated results will depend on the service.
