### ISSUE TITLE
Sign In

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#56]
# Description
Sign In

# Screenshot
![sign in with your government gateway account](https://cloud.githubusercontent.com/assets/2305016/22467704/8a2eb59a-e7bd-11e6-8311-c2c85febf833.png)

# Hackpad Discussion
https://designpatterns.hackpad.com/Sign-in-aVfhGsMS3b2

**Comment by stevenaproctor** [comment]
@gavinwye Repeats #19.

**Comment by gavinwye** [comment]
duplicate of #19
