### ISSUE TITLE
Call us

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#57]
# Existing Examples

![image](https://cloud.githubusercontent.com/assets/1752124/22467695/e8923a1e-e7c5-11e6-956b-d89495fa7c55.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467712/f448404c-e7c5-11e6-8f62-3fee942a102f.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467718/fc7217ca-e7c5-11e6-90ef-cc9789808c9b.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467726/043507d8-e7c6-11e6-8469-4c5e17e0a25a.png)

**Comment by stevenaproctor** [comment]
@gavinwye #18, #41, #52, #57 and #98 are similar. They are pages of content. Could this be a single pattern?

**Comment by gavinwye** [comment]
this is #98 so closing this
