### ISSUE TITLE
Beta banner

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#58]
# Existing Examples

![image](https://cloud.githubusercontent.com/assets/1752124/22467781/3af0854a-e7c6-11e6-9fe3-18447d2da7a4.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467806/5c9041e0-e7c6-11e6-9a5c-e0c227a8fa32.png)

# GOV.UK Pattern

https://www.gov.uk/service-manual/user-centred-design/resources/patterns/alpha-beta.html

**Comment by gavinwye** [comment]
This needs to be updated to take account of the new GOV.UK banner

**Comment by stevenaproctor** [comment]
Closed as it is part of the GOV.UK design system backlog.
