### ISSUE TITLE
Blue banner

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#60]
# Existing Examples

![image](https://cloud.githubusercontent.com/assets/1752124/22467978/03c00144-e7c7-11e6-94b9-441e5ae298d4.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467983/0d6ebeec-e7c7-11e6-9b10-6178d1466e18.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467995/155366b2-e7c7-11e6-87c3-ef26ea04dd10.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22468008/25efad8c-e7c7-11e6-9bb3-93b4a37a2c3a.png)

# GOV.UK Pattern

https://www.gov.uk/service-manual/user-centred-design/resources/patterns/alpha-beta.html

**Comment by gavinwye** [comment]
Discussed at the working group on 24/11/17 this is not either useful or unique.
This should not be used in services as it's something that should be reserved for prominent pages is government.

**Comment by stevenaproctor** [comment]
@gavinwye What about the user research panel banner and banners used in the personal tax account? Neither of those are mentioned above but do exist.

What do services do that have used a blue banner as described in this issue?
