### ISSUE TITLE
Save and continue

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#61]
# Existing Examples

![image](https://cloud.githubusercontent.com/assets/1752124/22468062/543296d2-e7c7-11e6-96ff-939511376697.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22468067/5941edd0-e7c7-11e6-88c1-caf4a4a7d8e9.png)

# Hackpad Discussion

https://designpatterns.hackpad.com/Save-and-return-new-C1074laOlwS

# Notes

Not sure that these are actually a pattern though. We should have a pattern for saving something but these things are just save buttons

**Comment by stevenaproctor** [comment]
@gavinwye Component?

**Comment by gavinwye** [comment]
Comments from London 

- Could be a component.
- We already have the save button and it can be edited (content wise). 
- Do we need another one with different content?
- When you “continue” you already “save” the content of the page (usually). May this create confusion with other buttons that don’t say “save” and only say “continue”?
- We think we need a green button with a content that may change depending on the context and action the user will make. Not fixing the content to the button.

**Comment by gavinwye** [comment]
Close this as the button is covered in elements

**Comment by jennifer-hodgson** [comment]
Same as #147 - continue discussion there.
