### ISSUE TITLE
Make a payment

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#62]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22468297/0a837c44-e7c8-11e6-8559-9846f25710a2.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22468233/d72de334-e7c7-11e6-994f-baeaece8f516.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22468268/f2b5eee4-e7c7-11e6-8949-24a8793b2431.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22468172/b563318c-e7c7-11e6-89eb-f334ce6eb0ad.png)

# Hackpad Discussion

https://designpatterns.hackpad.com/Payment-screens-c6ujPWbCoeY

**Comment by rpowis** [comment]
Do we need a HMRC pattern for payment - or does all Government need a pattern for online payments?

**Comment by stevenaproctor** [comment]
@gavinwye I think we are changing suppliers soon. But I agree with @rpowis. Why have a different pattern? A lot of departments need to get money from people for all kinds of things.

**Comment by joelanman** [comment]
Do you know which services use this pattern?

**Comment by jennifer-hodgson** [comment]
This is [on the GOV.UK backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/79).

**Comment by mikeash82** [comment]
Contributions moved to [Pay for something](https://github.com/alphagov/govuk-design-system-backlog/issues/79) on the GOV.UK issues backlog
