### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#63]
## Screenshot
Asking for a name
![image](https://cloud.githubusercontent.com/assets/868772/22468503/65685a6a-e7c0-11e6-8742-54a999c46041.png)

We also tell people the name we have for them but this is done as part of #4 (HMRC header)

**Comment by gavinwye** [comment]
This pattern is in the service manual: https://www.gov.uk/service-manual/design/names

**Comment by MarkKeeling** [comment]
This pattern is ideal for HMRC's needs (due to tech constraints) however wider XGov does consider a single entry more acceptable.

**Comment by stevenaproctor** [comment]
@gavinwye Any idea why the service manual says you do not have to mark a middle name as optional but elements says you do? See https://www.gov.uk/service-manual/design/names#labelling-name-fields and http://govuk-elements.herokuapp.com/form-elements/#form-optional-fields

**Comment by russellthorn** [comment]
Register to vote have this page - https://www.registertovote.service.gov.uk/register-to-vote/name (but have omitted the optional label for the middle name)

**Comment by stevenaproctor** [comment]
@russellthorn The service manual actually says to leave the optional label off middle name. I assume it will be because people without middle names will know to leave it blank. And if you put it on people with middle names may decide to leave it out.

Maybe the pattern needs to be "Middle name, if you have one" or not ask for it at all. What happens if someone with a middle name leaves it blank?

**Comment by russellthorn** [comment]
@stevenaproctor I'm not sure what happens if you leave middle name blank, even though I re-registered to vote recently. I think it does nothing?

**Comment by gavinwye** [comment]
We should mention this in a larger name pattern taking account of #11 Previous names
- middle names
- company name
- trading name

**Comment by stevenaproctor** [comment]
Add examples to the Design System showing separate names. It is a use case that is allowed and explained in the documentation.

**Comment by mikeash82** [comment]
Moved to [Names](https://github.com/alphagov/govuk-design-system-backlog/issues/53) on the GOV.UK issues backlog
