### ISSUE TITLE
Create a password

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#64]
## Screenshot
![image](https://cloud.githubusercontent.com/assets/868772/22468716/472e5904-e7c1-11e6-9bcf-39d197bc6801.png)

**Comment by stevenaproctor** [comment]
@gavinwye Is this a pattern? Is it going to be used in more than one place?

**Comment by gavinwye** [comment]
I'm not sure how many services have a need for this. More investigation is necessary with this.

**Comment by russellthorn** [comment]
We have this page. Or at least it's an off shot of registering a company if you don't have a gov gateway sign in.
https://www.tax.service.gov.uk/government-gateway-registration-frontend?accountType=organisation&continue=%2Fregister-your-company%2Fpost-sign-in&origin=company-registration-frontend

Not sure it's a pattern, but if it were to be a pattern I think it definitely needs work to improve it, I think.

**Comment by gavinwye** [comment]
Useful and Unique but requires more work

**Comment by ignaciaorellana** [comment]
Hi @gavinwye is this more about related to creating user accounts??

**Comment by gavinwye** [comment]
@ignaciaorellana yes and the title is not a true reflection of what it is. I'll update it from 'Personal details' to 'Create a password'

**Comment by rpowis** [comment]
@gavinwye this doesn't look password specific though. are you suggesting that it should be but the screenshot has too much in it? if not, then it feels more like "Create an account".

**Comment by MarkKeeling** [comment]
@gavinwye 
One thing to consider is that all patterns that relate to Government Gateway such as this one will probably be completely different in less than 12 months. The BAS project is currently looking at different approaches to more high level pain point regarding the Government Gateway journeys.

**Comment by jennifer-hodgson** [comment]
[Published](https://design-system.service.gov.uk/patterns/passwords/) on GOV.UK Design System
