### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#66]
## Screenshot
![image](https://cloud.githubusercontent.com/assets/868772/22468895/fbdee58a-e7c1-11e6-89a6-6c41feab184c.png)

## Other links
There is a placeholder page on the GOV.UK hackpad for this: https://designpatterns.hackpad.com/dashboards-yAgTohrGHDS

**Comment by adamliptrot-oc** [comment]
Inheritance Tax has a similar pattern for showing estate reports in progress.

**Comment by stevenaproctor** [comment]
@gavinwye Will users understand "dashboard"? Will people using the design system?

**Comment by gavinwye** [comment]
is this not another version of a task list #38?

**Comment by adamliptrot-oc** [comment]
This is not a dashboard, but naming aside a pattern should exist for displaying large amounts of data which some services need to do.

**Comment by gavinwye** [comment]
We don't currently have a need for this in services - but if we do in the future. It would be something that the team who need it should develop it at that time.

Propose this to be closed

**Comment by russellthorn** [comment]
Has anyone looked at performance platform for this? https://www.gov.uk/performance

**Comment by russellthorn** [comment]
A good dashboard to look at - https://www.gov.uk/performance/register-to-vote

**Comment by adamliptrot-oc** [comment]
Added an issue for Tiles / Cards #137

**Comment by gavinwye** [comment]
Add a description to the design system about dashboards linking to the examples @russellthorn has given above.

**Comment by stevenaproctor** [comment]
This issue has been closed because there is part of the GOV.UK Design System.
