### ISSUE TITLE
Bank account details

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#69]
## Screenshot
Collecting bank account details
![image](https://cloud.githubusercontent.com/assets/868772/22469240/38b3d03c-e7c3-11e6-9d5d-4c0167cf1872.png)

Displaying bank account details
![image](https://cloud.githubusercontent.com/assets/868772/22469254/450b114c-e7c3-11e6-8fef-8f71096aec6e.png)

**Comment by alex16wake** [comment]
![image](https://user-images.githubusercontent.com/24815473/28575463-e35c6260-7148-11e7-8d22-bb2faa9948b4.png)

**Comment by stevenaproctor** [comment]
@gavinwye This should be a GOV.UK pattern.

**Comment by adamliptrot-oc** [comment]
Do we have any UR on the best way to present a Sort-code input? With the 3 input option shown in one of the screenshots how would you mark up that? It feels like the label for each input would be odd for screenreaders.

**Comment by jenrahm** [comment]
![image](https://user-images.githubusercontent.com/33151742/32222471-4d49370e-be31-11e7-856d-f264dcb59827.png)



![image](https://user-images.githubusercontent.com/33151742/32222484-58a54412-be31-11e7-9751-cbbbadecc889.png)

**Comment by jennifer-hodgson** [comment]
Repayments service
Prototype here: https://www.prototypes.tax.service.gov.uk/repayments-prototype/version2/refund-and-bank-details
![repayments](https://user-images.githubusercontent.com/29708171/37155957-9379a32a-22dc-11e8-8c29-5c7be681dc0a.png)

**Comment by jennifer-hodgson** [comment]
This is on the GOV.UK backlog, differentiated from [Payment card details](https://github.com/alphagov/govuk-design-system-backlog/issues/80) and [Pay for something](https://github.com/alphagov/govuk-design-system-backlog/issues/79), [here](https://github.com/alphagov/govuk-design-system-backlog/issues/149). 

Therefore I would suggest that we contribute these examples and findings there and no pursue this for our HMRC Design Patterns.

**Comment by mikeash82** [comment]
Contributions moved to [Payment card details](https://github.com/alphagov/govuk-design-system-backlog/issues/80) on the GOV.UK issues backlog
