### ISSUE TITLE
Data in a table

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#7]
# Description

Displaying data in a table

# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22465250/081884f2-e7bb-11e6-9c84-5bbe5a5c8035.png)

# GOV.UK Pattern

https://govuk-elements.herokuapp.com/data/#data-in-a-table

**Comment by gavinwye** [comment]
This is in elements http://govuk-elements.herokuapp.com/data/#data-in-a-table so we shouldn't be doing this.

**Comment by gavinwye** [comment]
Create another issue for tables at HMRC
