### ISSUE TITLE
Progress indicators

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#72]
## Screenshots
![image](https://cloud.githubusercontent.com/assets/868772/22469566/5fc57f9e-e7c4-11e6-80e4-846db6ab8925.png)

Tracking forms
![image](https://cloud.githubusercontent.com/assets/868772/22469578/691c99e2-e7c4-11e6-9ec3-945063ab4110.png)

Your progress in an application
![image](https://cloud.githubusercontent.com/assets/868772/22469587/7667e5fc-e7c4-11e6-85b5-54b29436a3d9.png)

## Other links
Service manual: https://www.gov.uk/service-manual/design/progress-indicators

**Comment by stevenaproctor** [comment]
@gavinwye Similar to #45.

**Comment by stevenaproctor** [comment]
And #38.

**Comment by philsherry** [comment]
How are we conveying this information to screen readers? 

I know how the AMLS one works (I built it), but how does AWRS handle that? Received, Processed, Decision. As a sighted user, I can see that I've completed the first step, I'm on the second, and there's a final step to come. How is a screen reader user getting that information? 

Claim a tax refund: as a sighted user, I can see that I've completed the first step and there are three steps to go. How is a screen reader user getting that information? 

I'd expect some context around those things as they're read out. We need to start putting in a lot more thought around these things. Screen reader first, yo!

**Comment by philsherry** [comment]
For clarity, the AMLS version says the following in VoiceOver when you key through to a completed section: "[section name]. This section is completed. Link. You can edit this section."

**Comment by vickytnz** [comment]
The AWRS and PTA examples are pretty much delivery trackers - looking at similar services in this respect may give some possible solutions?

**Comment by gavinwye** [comment]
We need to decide if we need this

**Comment by gavinwye** [comment]
Discussed at the working group on 24/11/17 and closed this as there is a GOV.UK pattern for indicating progress for users.

However, we need a pattern that talks about how to track something.
