### ISSUE TITLE
Free text entry

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#74]
## Screenshot
Single line with limit
![image](https://cloud.githubusercontent.com/assets/868772/22469802/1da76b58-e7c5-11e6-9850-d86d6b9d861b.png)

Multi-line
![image](https://cloud.githubusercontent.com/assets/868772/22469827/2e3f5606-e7c5-11e6-9415-a0de5b6b5b4e.png)

## Other links
GOV.UK hackpad: https://designpatterns.hackpad.com/Text-boxes-imgij2JcsHO

**Comment by stevenaproctor** [comment]
@gavinwye Component?

**Comment by gavinwye** [comment]
this is just a textarea and is covered in element
