### ISSUE TITLE
Property details

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#75]
## Screenshot
![image](https://cloud.githubusercontent.com/assets/868772/22469926/814978ea-e7c5-11e6-97b6-99ac9742feee.png)

![image](https://cloud.githubusercontent.com/assets/868772/22469957/9c6955e6-e7c5-11e6-8f0e-6e5c62048fba.png)

![image](https://cloud.githubusercontent.com/assets/868772/22469968/a37b498e-e7c5-11e6-9529-ec72f69647e3.png)

![image](https://cloud.githubusercontent.com/assets/868772/22469971/a706338e-e7c5-11e6-9e36-5f0d56f2361d.png)

**Comment by gavinwye** [comment]
It looks from the screenshots that this pattern is more like a collection of pages that gather information about a property

**Comment by stevenaproctor** [comment]
@gavinwye I agree with your comment. It is also similar to #13 and #74.

**Comment by gavinwye** [comment]
This is about asking users for property details I wonder how different that is from collecting an address.

**Comment by stevenaproctor** [comment]
This issue was closed because there was not enough information about if it is general enough to be a pattern or if it needs to be specific for each service.
