### ISSUE TITLE
Access code

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#76]
## Screenshot
Send access code
![image](https://cloud.githubusercontent.com/assets/868772/22471792/4f49a1fc-e7cb-11e6-95eb-9d74e2f30c8c.png)

Input access code
![image](https://cloud.githubusercontent.com/assets/868772/22470084/06502b10-e7c6-11e6-9b4c-fe454cd775e3.png)

**Comment by stevenaproctor** [comment]
@gavinwye Is this not just a variation of #74?

**Comment by gavinwye** [comment]
I think this is probably a component of a sign in pattern

**Comment by stevenaproctor** [comment]
This issue was closed because it is part of the 2-step verification sign in microservice. It does not need to be documented.
