### ISSUE TITLE
Exit survey and feedback

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#77]
## Screenshot
Horizontal radio buttons
![image](https://cloud.githubusercontent.com/assets/868772/22470135/34b20640-e7c6-11e6-88fd-77e5b1d1bb4f.png)

Vertical radio buttons
![image](https://cloud.githubusercontent.com/assets/868772/22470169/50a0172a-e7c6-11e6-94d5-b0ffcc673cb6.png)

## Other links
Service manual: https://www.gov.uk/service-manual/design/feedback-pages

**Comment by gavinwye** [comment]
@stevenaproctor has done work on [feedback pages](https://hmrc-feedback.herokuapp.com/)

**Comment by stevenaproctor** [comment]
@gavinwye Repeat of #46.

**Comment by gavinwye** [comment]
duplicate of #46
