### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#78]
## Screenshot
![image](https://cloud.githubusercontent.com/assets/868772/22470228/800e9978-e7c6-11e6-9e5d-58cb41603ee4.png)

This pattern is related to #77 (Exit surveys)

**Comment by stevenaproctor** [comment]
@gavinwye Part of #77 or #46 rather than on its own.

**Comment by gavinwye** [comment]
closed because of what @stevenaproctor says above
