### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#81]
## Screenshot
![image](https://cloud.githubusercontent.com/assets/868772/22470682/f59fcc38-e7c7-11e6-89b3-705fa455d7e7.png)

This is probably an element

**Comment by Guillermoreno** [comment]
We tested the version above on mobile and users didn't see the links/tabs, adding a light grey background fixed that issue
<img width="661" alt="screen shot 2017-11-06 at 15 33 12" src="https://user-images.githubusercontent.com/8657018/32448808-dce48442-c307-11e7-86a6-2597218b5df3.png">

**Comment by stevenaproctor** [comment]
The issue was closed because it will be covered by the GOV.UK Design System.

**Comment by gordonmcmullan** [comment]
Reopened as a result of a request in team-sdt and a discussion in the team
