### ISSUE TITLE
List - tabular data

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#84]
## Screen shot
![image](https://cloud.githubusercontent.com/assets/868772/22470896/a30d8504-e7c8-11e6-994f-8561ea27446b.png)

**Comment by stevenaproctor** [comment]
@gavinwye Same as #7.

**Comment by gavinwye** [comment]
This is in elements http://govuk-elements.herokuapp.com/data/#data-in-a-table so we shouldn't be doing this.

**Comment by gavinwye** [comment]
Create another issue for tables at HMRC
