### ISSUE TITLE
Two factor authentication (2FA)

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#86]
## Screen shot
![image](https://cloud.githubusercontent.com/assets/868772/22471229/b310d0fe-e7c9-11e6-9711-99e81d290e35.png)

This is more likely to be a service pattern than a standalone pattern. In that case, we should probably have this service pattern documented in the design language so that we have "one source of truth"

**Comment by stevenaproctor** [comment]
I think 2SV is used every time a Government Gateway account is used for the first time.

This page could be styled like a normal done page.

**Comment by stevenaproctor** [comment]
This issue has been closed because it is the same as #40.
