### ISSUE TITLE
Cookie banner link

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#87]
## Description 
We need to tell users that we are using cookies in our services

## Screenshot
to do

**Comment by gavinwye** [comment]
There is an issue relating to this pattern on the [GOVUK-template](https://github.com/hmrc/govuk-template/issues/2)

**Comment by stevenaproctor** [comment]
@gavinwye Same as #88.

**Comment by gavinwye** [comment]
this is just the cookie banner from GOV.UK we have a different link to a cookie page so we need to document that somewhere.

**Comment by stevenaproctor** [comment]
@gavinwye Document it as part of #88?

**Comment by jennifer-hodgson** [comment]
This is a GOV.UK pattern - [Cookie banner](https://github.com/alphagov/govuk-design-system-backlog/issues/12) and [Cookie page](https://github.com/alphagov/govuk-design-system-backlog/issues/13) are on their backlog.

**Comment by stevenaproctor** [comment]
The only difference is the link, which goes to HMRC's cookie policy. I think the banner and link come from the standard page template. Is that worth documenting?

**Comment by jennifer-hodgson** [comment]
Let's comment in a line about the link going to respective departmental policies - if they don't have that covered already.

**Comment by mikeash82** [comment]
Moved to [Cookie banner](https://github.com/alphagov/govuk-design-system-backlog/issues/12) and [Cookie page](https://github.com/alphagov/govuk-design-system-backlog/issues/13) on the GOV.UK issues backlog
