### ISSUE TITLE
Single radio selection

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#9]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22465648/fc91b21e-e7bc-11e6-94be-8e5453956665.png)

# GOV.UK Pattern

https://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons

**Comment by gavinwye** [comment]
The GDS recently updated the radio button element. We need to update this in the HMRC version

**Comment by stevenaproctor** [comment]
@gavinwye There is nothing in elements about a single radio button. Should this even be a thing?

**Comment by philsherry** [comment]
Why would there ever be a single radio button? That smells funny. Is this just another type of "click here to confirm" pattern?

**Comment by rpowis** [comment]
This was found during discovery so it was documented. Before we really had a defined understanding of what constitutes a component or a pattern.

> Is this just another type of "click here to confirm" pattern?

Looks like it. I guess the norm is to use a checkbox, although I don't see why it can't just be a continue button?

Also worth mentioning that the title would indicate that it's the radio button as a component that's being proposed here, although the screenshot makes it look like a pattern.

**Comment by stevenaproctor** [comment]
@rpowis Making people select a radio or checkbox is an extra selection that is unnecessary. Suitable content and a button makes more sense.

**Comment by gavinwye** [comment]
This is not something that we want to encourage
