### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#90]
Original conversation relating to this in HMRC slack: https://hmrcdigital.slack.com/archives/community-ux/p1485950134000025

As reccomended bny Chris Moore to Phil Sherry
[page title] - [section name] - [service name] - GOV.UK
[page title] should mirror `h1` on that page.

**Comment by gavinwye** [comment]
Page titles get passed to google analytics, therefore, it's important that they don't contain any personal information.

**Comment by gordonmcmullan** [comment]
Discussion Summary from the hackday

![img_20180312_153153](https://user-images.githubusercontent.com/234825/37340453-17cdacfc-26b6-11e8-9f35-2c20078cd003.jpg)

**Comment by stevenaproctor** [comment]
On the [GOV.UK Design System backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/157).

**Comment by sophie-still** [comment]
Is the same format used for page titles on internal HMRC services? (I've heard in the past that we shouldn't add "- GOV.UK" on internal services but haven't seen any official guidance

**Comment by Jon-Rowe-HMRC** [comment]
Hi @sophie-still my suggestion is that we should change our page title guidance to exclude 'GOV.UK' from internal page titles. I'll look into making the amend.

**Comment by dombillington** [comment]
I've been looking at the guidance for showing PII in page titles. It's true that PII appearing in analytics packages is a problem, but I think we should also mention the risk of PII in page titles showing in places like browser history, etc. This should be a consideration when making this decision.

I'm supporting the childcare service and considering a scenario where someone uses the service on a shared computer. Exposing the child's name in the browser history could be an issue here.
