### ISSUE TITLE
Is there anything wrong with this page?

### ISSUE THREAD

**Issue by gordonmcmullan** [hmrc/design-patterns#92]
## Description

When a user wants assistance with an action they're attempting to complete on a page, there is a link which displays a form asking for information from the user which will be useful in providing them assistance.

## Screenshot of current live service:

![image](https://cloud.githubusercontent.com/assets/234825/22735065/fe7b5c4a-edef-11e6-8efd-4771ef5b1a9a.png)

## Slack Discussion

A slack [discussion](https://hmrcdigital.slack.com/archives/community-ux/p1486047900000074) on [#community-ux](https://hmrcdigital.slack.com/archives/community-ux) suggested that it would be useful to make the form more service specific.

The discussion also suggests that the answers provided to the question 'What were you doing?' were sometimes not resulting in useful responses from users.

**Comment by philsherry** [comment]
While the fields for Name and Email are fine (although, `type="email"` would be a good addition to the latter…), the question fields should really be `textarea` rather than `input`.

It could do with behaving a bit nicer, too. With no JS, it just appears – that's fine, but this link is still sat in the page: `<a class="report-error__toggle js-visible" id="get-help-action" href="Action(parser=BodyParser(anyContent))">Is there anything wrong with this page?</a>`. That `href` is _nasty_.

**Comment by gavinwye** [comment]
If the service that's using this pattern isn't set up in Deskpro the Deskpro team don't know where the feedback is coming from. Maybe we could add a hidden field with the service name to this form to make it easier for the Deskpro users.

**Comment by jennifer-hodgson** [comment]
On BTA, we're also having issues with this pattern. Currently our users are tending to use this pattern to report issues with their tax affairs, which is generating a number of rogue, misdirected Deskpro tickets. It appears the distinction between "webpage issues" and "tax issues" isn't clear enough in the current content. 

I would suggest that we need to make clearer that this form is for reporting issues with the page and/or the digital service, and also perhaps direct users towards the correct place for reporting issues with their tax affairs.

**Comment by stevenaproctor** [comment]
I agree with @jennifer-hodgson. People tend to ignore the "Don't include any personal or financial information. For example, your National Insurance or credit card numbers." that is at the top of the form.

A lot of services changed the link to "Is there anything wrong with this page?" to try and stop this kind of behaviour but I do not think this has had the effect people were hoping for. Plus, all the content on the form is still geared towards "get help".

**Comment by gavinwye** [comment]
`<div> 
                <br>      <br>        
                 <p>
                  <a href="#support" class="report-error" id="get-help-action" onclick="$('#support').toggle();return false;">Get help with this page</a></p>
                  <small class="hidden-help" id="support" style="display: none;">
                
                  <div id="report-error-partial-form" class="report-error__content">
                  <h3 class="heading-medium">Get help using this service</h3>
                  <p>
                     Don't include any personal or financial information. For example, your National Insurance or credit card numbers.
                  </p>
                  <form action="" method="" class="form--feedback" novalidate="novalidate">
                      <fieldset>
                      
                      <div class="form-group-compound">
                              <label for="report-name" class="form-label">Name</label>
                              <input id="report-name" class="form-control-3-4" name="report-name" type="text" data-rule-letterswithbasicpunc="true" data-rule-required="true" data-msg-required="Please provide your name." aria-required="true">
                          </div>
                          <div class="form-group-compound">
                              <label for="report-email" class="form-label">Email</label>
                              <input id="report-email" class="form-control-3-4" name="report-email" type="email" data-rule-required="true" data-rule-email="true" data-msg-required="Please provide your email address." aria-required="true">
                          </div>
                          <div class="form-group-compound">
                              <label class="form-label" for="text">What where you doing?</label>
                              <input class="form-control-3-4" id="text" name="report-action" type="text" data-rule-required="true" data-msg-required="Please enter details of what you were doing." aria-required="true">
                          </div>
                          <div class="form-group-compound">
                              <label for="report-error" class="form-label">What do you need help with?</label>
                              <input id="report-error" class="form-control-3-4" name="report-error" type="text" data-rule-required="true" data-msg-required="Please enter details of what went wrong." aria-required="true">
                          </div>
                         
                          <input type="hidden" name="isJavascript" value="true">
                          <input type="hidden" name="referrer" value="https://web-qa.tax.service.gov.uk/mdtp/registration">
                          <div class="form-field">
                              <button id="report-submit" class="button" type="submit" data-journey-click="">Send</button>
                          </div>
                      </fieldset>
                  </form>
                  </div></small></div>`

**Comment by stevenaproctor** [comment]
@gavinwye This is a GOV.UK pattern. It is the same as what is on GOV.UK but with name and email address added to it.

**Comment by gavinwye** [comment]
this should be grouped under #46

**Comment by JamesPBoyle** [comment]
@olirose @JSJohal - this is the design system thread for the get help with this page component. 

@stevenaproctor, Oli and Jas are working on Making Tax Digital for Business. They did some user research on the get help form late last year. We've had a few chats about ways to improve the form. 

We've currently agreed a process where Oli and Jas will kick around ideas. They'll touch base with platform services to confirm if the ideas are technically feasible to implement. Then they'll look to do user testing. I'm sure they'd welcome the ideas you had for the form.

We are expecting a bit of a lead time on this work. Rather than specifically testing designs in unique UR sessions, we are going to test the new patterns if users get stuck during a journey.

**Comment by jennifer-hodgson** [comment]
This, again, is GOV.UK - we could feed our findings about people supplying the wrong kind of information and any new findings from the new version @stevenaproctor and I worked on to them. Cannot seem to find an issue on their backlog, though...

**Comment by stevenaproctor** [comment]
We could create an issue on the GOV.UK Design System backlog. Not sure if other government departments use something similar.

**Comment by jennifer-hodgson** [comment]
Let's do that - and add in the stuff we worked on in early summer.

**Comment by mikeash82** [comment]
Upstreamed to the GOV.UK issues backlog https://github.com/alphagov/govuk-design-system-backlog/issues/170
