### ISSUE TITLE
Password reveal

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#93]
# Description
Password Reveal to show the password a user has entered into an input

# Screenshot
![2e733798-c686-11e5-91c6-457640f364dc](https://cloud.githubusercontent.com/assets/2305016/22986365/2da8d1ba-f3a3-11e6-91d6-c59d2d60047c.gif)

**Comment by feedmypixel** [comment]
### Code
https://github.com/hmrc/assets-frontend/blob/master/assets/javascripts/modules/passwordReveal.js

**Comment by stevenaproctor** [comment]
@gavinwye Crossover with #64.

**Comment by gavinwye** [comment]
I'm not sure we should be doing this at all.

**Comment by gavinwye** [comment]
We don't currently have a need for this in services - but if we do in the future. It would be something that the team who need it should develop it at that time.

We don't think this is being used in a service and there are only a few pages across HMRC that this could be used.

**Propose this to be closed**
