### ISSUE TITLE
Other names

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#94]
Related to [issue 11](https://github.com/hmrc/design-language-documentation/issues/11)

## Screenshot

This pattern only relates the lower portion of this screenshot for other names

![image](https://cloud.githubusercontent.com/assets/868772/24797437/27575a4e-1b89-11e7-8449-5e4a2d978909.png)

**Comment by gavinwye** [comment]
# Questions
1. why are people know by other/alternative names?
2. why does government care about this?
3. why does HMRC care about this?
4. what's the difference between an alternative name and a nickname?
5. how does government/HMRC use an alternative name?
6. are there any security considerations with other names?

**Comment by MarkKeeling** [comment]
While we think there is a need for this pattern, we think the differing interaction of a single entry may confuse. It would be good to see further user research around it.

**Comment by russellthorn** [comment]
Is there a need to differentiate this pattern from https://github.com/hmrc/design-patterns/issues/11 are they really different?

Maybe have 1 pattern instead of 2 for this?

**Comment by stevenaproctor** [comment]
We may need a name pattern that covers:

* current name
* previous name
* other names

Then have something for organisations with different trading names too.

**Comment by stevenaproctor** [comment]
This issue was closed because it should be covered by #63.
