### ISSUE TITLE
Enter or find an address

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#96]

**Comment by alex16wake** [comment]
![image](https://user-images.githubusercontent.com/24815473/28574095-c09b33ea-7144-11e7-93ec-6cd449b86422.png)

If NO

![image](https://user-images.githubusercontent.com/24815473/28574203-2714a78c-7145-11e7-8e6d-d5472971c720.png)

If YES

![image](https://user-images.githubusercontent.com/24815473/28574123-d91f9c12-7144-11e7-8717-c81ca2c1c635.png)

If DIRECT MATCH from search

![image](https://user-images.githubusercontent.com/24815473/28574269-58b687f6-7145-11e7-906c-032906a8524e.png)

If NO DIRECT MATCH

![image](https://user-images.githubusercontent.com/24815473/28574367-ac6a455e-7145-11e7-8caf-32a8b900b318.png)

"The address is not on the list"

![image](https://user-images.githubusercontent.com/24815473/28574424-dcf1c3f0-7145-11e7-9813-2be9958a5417.png)

Confirm your address

![image](https://user-images.githubusercontent.com/24815473/28574505-1a1cb78a-7146-11e7-8b9e-5001390247a8.png)


EDGE CASES
User exceeds character limit for manual entry

![image](https://user-images.githubusercontent.com/24815473/28574571-404df13a-7146-11e7-9d32-35a9f4166363.png)

User enters a valid address but it is too long for the system to store

![image](https://user-images.githubusercontent.com/24815473/28574596-54eaf53e-7146-11e7-8c86-b5c3e46ba1a1.png)

**Comment by gavinwye** [comment]
Work started in https://github.com/hmrc/design-patterns/pull/113

**Comment by stevenaproctor** [comment]
@gavinwye Similar to #37.

**Comment by jenrahm** [comment]
![image](https://user-images.githubusercontent.com/33151742/32222691-2f0001d2-be32-11e7-83db-39faf29f8fd2.png)

![image](https://user-images.githubusercontent.com/33151742/32222711-487f9b4a-be32-11e7-9674-36d8f339db80.png)

**Comment by jennifer-hodgson** [comment]
This is [published on the GOV.UK Design System](https://design-system.service.gov.uk/patterns/addresses/) - I believe the genesis of us having a separate issue was so we could have an HMRC variant. Suggest we upstream such a variant rather than having a separate issue.

**Comment by mikeash82** [comment]
Continue discussions in [Addresses](https://github.com/alphagov/govuk-design-system-backlog/issues/31) issue on GOV.UK baacklog
