### ISSUE TITLE
Signpost

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#98]
Use this pattern when there is a problem with a users account and they need to contact HMRC

### Example
![image](https://cloud.githubusercontent.com/assets/868772/26395204/41825e16-4067-11e7-8715-9c445f4d360b.png)

**Comment by matthewjbarker** [comment]
![screenshot-personal-tax-account herokuapp com-2017-05-24-09-56-13](https://cloud.githubusercontent.com/assets/22151292/26395622/88d38136-4068-11e7-82a8-03ea06bd223b.jpeg)

**Comment by gavinwye** [comment]
@matthewjbarker could you provide some details about why this exists and what problem it solves for users, please?

**Comment by stevenaproctor** [comment]
@gavinwye @matthewjbarker We are supposed to say sign in and sign out, not log in and log out. I would also wonder why it says "MCI error". That will mean nothing to someone signing in.

**Comment by jennifer-hodgson** [comment]
I think the [issue on the GOV.UK Design System backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/10) is similar enough for whatever we have to be at most a variant.

**Comment by mikeash82** [comment]
Contributions moved to [Contact a department](https://github.com/alphagov/govuk-design-system-backlog/issues/10) on the GOV.UK issues backlog
